### ISSUE TITLE
Supprimer la pagination (côté serveur) de la page d'édition du matériel d'un événement

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#115]

**Comment by polosson** [comment]
@Donov4n On avait parlé d'éventuellement avoir la possibilité d'utiliser un listing "virtualisé", mais avec `vue-table-2` il s'agit une feature disponible uniquement en version premium... Donc on va laisser tomber pour le moment.

**Comment by Donov4n** [comment]
🎉
