### ISSUE TITLE
Différencier la période de mobilisation du matériel de la période facturée

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#124]
Il s'agit ici d'avoir deux périodes associées à un événement :

- Période de mobilisation : temps pendant lequel le matériel est considéré comme sorti du parc.
- Période de facturation : dates permettant de calculer le montant total en tenant compte du calcul dégressif.

**Comment by Donov4n** [comment]
Implémenté dans la 0.24, cette version sortira d'ici quelques semaines, sauf imprévu, au moment ou j'écris.
