### ISSUE TITLE
Wrong testDatabase when different from robert2_test

### ISSUE THREAD

**Issue by adamlarat** [Robert-2/Robert2#128]
This issue should be labeled as 'bug'. I can't…

My database name is 'robert12' but the test on the server side looks for the test database 'robert2_test' instead of 'robert12_test'. 
![Capture d’écran de 2021-04-26 11-12-24](https://user-images.githubusercontent.com/1625270/116058637-5363b480-a680-11eb-98cf-79582436388c.png)

The reason for that is that in `Config\Config::getDbConfig()`, the default dbConfig is first loaded (with 'database' and 'testDatabase' set to 'robert2' and 'robert2_test' respectively) and then overwritten with the local configuration stored in src/App/Config/settings.json, where the variable 'testDatabase' does not appear. 
What does not work is the following three lines : 
`
if (isTestMode()) {
  $dbConfig['database'] = $dbConfig['testDatabase'];
}
`
since the correct 'database' variable is overwritten with the default (and wrong) 'testDatabase' name. 

I see two ways to correct this problem : 
1) add the corresponding 'testDatabase' line to the src/App/Config/settings.json config file when it is generated
2) Replace the three wrong lines above by:
`
if (isTestMode()) {
  $dbConfig['testDatabase'] = sprintf('%s_test', $dbConfig['database']);
  $dbConfig['database'] = $dbConfig['testDatabase'];
}
`

Personally, I would go for the second solution. Any way, if you agree, I can create a pull request to cope with this problem.

Cheers, 

Laden

**Comment by adamlarat** [comment]
Désolé, je vois que toutes vos issues sont rédigées en français. J'ai rédigé en anglais par habitude…

**Comment by polosson** [comment]
Hello Laden, merci pour ce report !

En effet, dans ce repo on peut discuter en français sans problème, nous n'avons pas de contributeur non-francophone pour le moment... Je sais que la plupart des entreprises de dev considèrent ça comme une mauvaise pratique, mais chez nous on préfère discuter dans notre langue maternelle, pour éviter les confusions et gagner du temps (même si on maîtrise parfaitement l'anglais lu et écrit, hein :sweat_smile:)

À propos du sujet de ce ticket, c'est intéressant mais je pense que dans un premier temps, il faudrait se contenter d'ajouter simplement une ligne `"testDatabase": "robert12_test"` dans ton fichier local `settings.json`.

En effet, il se pourrait très bien qu'on ait envie de mettre complètement autre chose qu'un suffixe `_test` pour notre DB de test, et se baser sur le nom de la DB normale ne devrait pas être un pré-requis, à mon avis.

En conclusions, pour laisser une plus grande liberté je pense (et ça n'engage que moi) qu'il vaut mieux laisser comme ça pour le moment. Par contre, il manque peut-être un peu de documentation sur le sujet, un petit texte dans le `CONTRIBUTING.md` qui expliquerait comment renommer la DB de test : en ajoutant simplement son nom entier dans le fichier `settings.json`.

Cheers !

**Comment by adamlarat** [comment]
Ouais c'est ce que j'ai fait pour le moment (de rajouter la ligne `"testDatabase": "robert12_test"` dans `settings.json`). 
Une troisième solution c'est de dire dans le `CONTRIBUTING.md` que la DB de test s'appelle `robert2_test`, point, quelque soit le nom de la DB du `settings.json`. Et je trouve que ça a du sens quand on a plusieurs install. Ma DB s'appelle `robert12` parce que j'ai fait plein de merdes depuis la migration à la v0.12 et c'est pratique d'avoir plusieurs instances sur lesquelles basculer. Par contre, les test peuvent tous être lancés sur la même DB, tant qu'ils ne sont pas lancés en même temps…
