### ISSUE TITLE
Numerous errors and failures when testing the server side

### ISSUE THREAD

**Issue by adamlarat** [Robert-2/Robert2#129]
Once I coped with the database name problem (Issue #128), I face numerous errors and failures when running the tests on the server side (the tests on the client side are 100% ok).
I am running `php composer.phar test` in the `server/` directory.
I think I followed all the instructions given in `CONTRIBUTING.md`. 
I am running Robert2 locally on Ubuntu 20.10. 
Do you see a reason for all theses errors and failures?

Chais même pas pourquoi j'écris en anglais… vous préférez le français ? 
Peu m'importe, en vrai ! 

[server_test.log](https://github.com/Robert-2/Robert2/files/6376030/server_test.log)

**Comment by polosson** [comment]
:smile: aucun souci Laden, merci pour tes messages en tout cas !

Est-ce que tu aurais un exemple (screenshot ou en texte) de ces erreurs, stp ?

**Comment by adamlarat** [comment]
Évidemment que j'ai fait un fichier `*.log`…
Évidemment que j'ai oublié de le joindre…
Évidemment je viens d'éditer mon issue !

**Comment by polosson** [comment]
OK, merci, en effet ça fait beaucoup de tests qui plantent ! :sweat_smile: 

Je pense qu'il y a un souci avec les fixtures... Est-ce que tu as bien un fichier `server/tests/Fixtures/tmp/schema.sql` qui est présent après avoir lancé les tests, et quel est le nom de la DB qu'il utilise (le `USE` à la première ligne de ce fichier) ?

**Comment by adamlarat** [comment]
USE robert12_test;
Voici les deux fichiers `*.sql` du dossier 
[tmp.tar.gz](https://github.com/Robert-2/Robert2/files/6376160/tmp.tar.gz)

**Comment by polosson** [comment]
OK, merci Laden !

Bon, je pense avoir trouvé d'où vient le souci : ça serait le dump des fixtures qui n'utilise pas la bonne base de données... Je continue à creuser de ce côté là et j'essaye de revenir avec une correction. Cheers !

**Comment by polosson** [comment]
Voilà qui devrait être corrigé @adamlarat ! Est-ce que tu veux bien checkout la branche `develop` et réessayer stp ?

Cheers

**Comment by adamlarat** [comment]
Nope, ça n'a rien changé. :-( J'ai pullé la branche develop, commit 7c0b0ba0c9…
J'ai essayé de créer une BD `robert2_test` et de relancer les test en supprimant la ligne `testDatabase` dans `settings.json` et ça ne change rien au pb, non plus. Donc ça ne semble pas avoir de lien avec l'issue #128. 
Quand je fais le diff de mon log avec le précédent, ya bcp d'erreurs avec `'robert12_test.estimates'`:
`447c447
< PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'robert12_test.estimates' doesn't exist
---
> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'robert2_test.estimates' doesn't exist
`

**Comment by polosson** [comment]
Hmmmm bizarre...

Est-ce que toutes les migrations sont bien déclenchées au lancement des tests ?  
Est-ce que la table `estimates` est bien présente dans le dump `server/tests/Fixtures/tmp/schema.sql` (vers la ligne 149) ?  
Es-tu bien certain de n'avoir aucune modification dans le code ?

Ici en local, tout fonctionne parfaitement, avec ou sans la ligne `testDatabase` dans les settings...

**Comment by adamlarat** [comment]
Je cherche, je cherche…
- Mon code est propre, `git status` est clean
- `estimates` est présent dans le dump `server/tests/Fixtures/tmp/schema.sql`, la migration est aussi affichée dans le log console 
`== 20210420090840 CreateEstimates: migrating
 == 20210420090840 CreateEstimates: migrated 0.1092s`
- Ce qui est nettement plus choquant c'est que la table `estimates` n'est pas présente dans la DB de test !!! Alors que les 24 autres tables créées le sont 8-(

Je vais continuer de traquer le problème par cette piste…

**Comment by adamlarat** [comment]
Dis Polosson, t'utilises quoi pour ton serveur SQL ?
Perso, chuis en MariaDB 10.3.25 et je me demande si c'est pas ça qui pose problème…
En effet, j'ai tenté de lancer manuellement les requêtes du dump `server/tests/Fixtures/tmp/schema.sql` directement sur la DB concernée et pour la table `estimates`, je me retrouve avec l'erreur : 
`ERROR 1163 (42000): Storage engine MEMORY doesn't support BLOB/TEXT columns`.

C'est la ligne ` 'materials' longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,` qui génère cette erreur et c'est cohérent avec la doc de MariaDB qui spécifie que le type `LONGTEXT` n'est pas supporté dans les memory tables.

Ya quand même un truc qui m'embête, c'est que exactement la même ligne est présente dans la création de la table `bills`. La table est parfaitement créée, y compris la column `materials`…
L'autre truc qui m'embête, c'est que la requête SQL n'aboutit vraisemblablement pas, alors que le test ne crache aucune erreur :-(

**Comment by polosson** [comment]
Ah, cool bien vu @adamlarat d'avoir lancé le dump manuellement !

Chez moi, le serveur MySQL est un `MySQL 8.0.23` (et non MariaDB). Cela dit, c'est étrange que tu aies `'materials' longtext` dans ton dump, chez moi j'ai `materials varchar(1024)`... Normalement, c'est remplacé dans `server/tests/Fixtures/RobertFixtures.php` à la ligne 118.

Ce que tu peux essayer, c'est d'ajouter la ligne suivante juste en dessous :

```php
        $dumpContent = str_replace('` longtext', '` varchar(1024)', $dumpContent);
```

Tu me dis si ça change quelque chose ?

**Comment by adamlarat** [comment]
Bingo!!!
Test OK, 338 tests, 758 assertions. 
Quelle bug de merde et quelle solution moche ! :-D
En vrai, j'ai pas compris grand chose ;-)
Je fais un pull-request ?

**Comment by polosson** [comment]
Si tu veux, yes ! Merci à toi :smiley:
