### ISSUE TITLE
Calendrier : il est toujours possible de supprimer un événement après confirmation

### ISSUE THREAD

**Issue by adamlarat** [Robert-2/Robert2#137]
Salut ! 
Ceci est un bug mineur : lorsqu'on clique sur un événement non-confirmé dans le calendrier, il est possible de l'agrandir, de le déplacer et de le supprimer avec la poubelle à droite. Si on double clique sur cet événement et qu'on le confirme, il n'est plus possible de l'agrandir et de le déplacer mais la poubelle apparaît toujours et elle est toujours active ! 
Je ne sais pas si c'est un bug de vis/timeline ou une erreur dans le code, j'arrive pas à trouver une solution rapide propre. 
En tout cas ce que j'arrive à faire, c'est de modifier cette ligne : 
```
diff --git a/client/src/pages/Calendar/index.js b/client/src/pages/Calendar/index.js
index 3ab6684..dcfb840 100644
--- a/client/src/pages/Calendar/index.js
+++ b/client/src/pages/Calendar/index.js
@@ -91,7 +91,7 @@ export default {
             });
         },
         onRemove: (item, callback) => {
-          if (isVisitor) {
+          if (isVisitor || item.isConfirmed) {
             return;
           }

```
La poubelle est toujours affichée, mais elle n'est plus active, il n'est plus possible de supprimer l'événement. 
C'est moche, je le conçois, mais ça résout une partie du problème…

**Comment by polosson** [comment]
Salut @adamlarat et merci pour ton retour !

En effet, c'est un bug connu, et ta solution est bien celle qu'on voulait faire ! C'est pas l'idéal yes, mais c'est mieux que rien, c'est sûr !

Merci en tout cas ! :)

**Comment by adamlarat** [comment]
Merci @polosson . Du coup je suis allé fouillé un peu chez vis-timeline et j'ai vu l'issue 451 et j'ai trouvé la solution. 
Dans `node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js`, la fonction qui gère le deleteButton est `_repaintDeleteButton`. 
Le deleteButton est créé lorsque l'événement est sélectionné, éditable et n'existe pas `if (this.selected && editable && !this.dom.deleteButton)` mais il n'est détruit que lorsqu'il existe et n'est plus sélectionnée : `else if (!this.selected && this.dom.deleteButton)`. C'est exactement ce qu'on observe. 
Pour qu'il soit détruit à la confirmation, il faut donc que la variable `editable` joue dans la condition de destruction : `else if ( (!this.selected || !editable) && this.dom.deleteButton)` fait le job. 
J'ai publié cette solution chez eux. Je dirais qu'il n'y a plus qu'à attendre… ;-)

**Comment by polosson** [comment]
C'est top @adamlarat !! Bien joué et merci pour tes contributions à vis-timeline aussi :)

C'est marrant parce que j'étais justement en train d'éplucher un peu le code de cette lib, car il y a d'autres problèmes avec les dernières versions de vis-timeline qui nous empêchent de passer aux dernières versions... J'essaye de te tenir au courant si j'arrive à les régler :)

**Comment by polosson** [comment]
Bon, alors il se trouve que la toute dernière version de vis-timeline est plantée à cause du merge de [cette pull-request](https://github.com/visjs/vis-timeline/pull/910)... Quand on fait la défiler, les éléments sur la timeline se baladent bizarrement à droite à gauche... C'est vraiment étrange. Mais vu le code de cette PR ça ne m'étonne qu'à moitié (il y a un fichier quasiment impossible à review tellement il y a de changements - qui doivent pour la plupart être dus à un Prettier ^^ - mais aussi du code en double et mis en commentaire...)

Bref, la version 7.4.8 n'est pas utilisable en l'état, et il faudrait se pencher sérieusement sur la lib pour trouver la cause du souci, avant d'ouvrir une issue qui détaille le problème en le documentant correctement.

Par contre, pour le problème qui nous occupe ici @adamlarat (bouton delete), est-ce que tu te sens de leur proposer une PR avec la modif que tu as trouvé, quand même ? Histoire qu'ils n'aient plus qu'à la merger, et que ton fix soit dispo dans la prochaine release... Would be great ! :slightly_smiling_face:

**Comment by adamlarat** [comment]
Elle est toute pétée la dernière version de vis-timeline !!!
J'essaye de mettre en place un MWE pour me convaincre que tout marche bien et que mon fix est bien fonctionnel sur un exemple tout bête et j'arrive rien à faire. Si je remonte de quelques commits, tout semble fonctionner normalement. 
C'est rageant, putain !!!

**Comment by adamlarat** [comment]
Salut @polosson, merci de ta compréhension. Je me suis un peu vénère mais j'avais besoin d'exprimer ma déception d'avoir perdu une demi-journée sur un truc aussi con. Chuis allé prendre une bonne douche chaude, ça va mieux ;-)
Pendant la douche j'ai décidé de faire une PR en partant sur le commit "humain" précédent. Je vais joindre un exemple, avec un build de timeline buggé, un build toupété et un build où l'exemple fonctionne.

**Comment by adamlarat** [comment]
Ma PR a été acceptée et reversée dans la branche `master` de `vis-timeline`. 
Du travail a été fait pour réparer le commit prérave. En tout cas mon MWE fonctionne correctement avec le build du HEAD du répo. 
Je sais pas quel problème vous aviez encore, mais ça serait intéressant de vérifier…
[MinimalWorkingExample.zip](https://github.com/Robert-2/Robert2/files/6564427/MinimalWorkingExample.zip)
Commit c1b2 : juste avant le commit tout pété
Commit 3b5c : version toute pétée
*working*       : version de ma PR
Commit b1e6 : HEAD actuel

**Comment by polosson** [comment]
Cool, merci pour ton taf là dessus @adamlarat !

Je n'ai pas retrouvé ta PR dans la liste de https://github.com/visjs/vis-timeline/pulls, aurais-tu un lien stp ?

Aussi, ils n'ont pas encore effectué de nouvelle release malheureusement, donc on va attendre qu'ils la sortent pour qu'on puisse mettre à jour les dépendances de notre côté et tester si ils ont bien corrigé le comportement bizarre.

En tout cas bien joué :slightly_smiling_face:  Cheers !

**Comment by adamlarat** [comment]
https://github.com/visjs/vis-timeline/pull/1067
