### ISSUE TITLE
Ajouter un paramètre de config permettant de ne pas utiliser le header `Authorization`

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#141]
Certains serveurs mutualisés (comme ceux de Ionos par exemple) ne permettent pas l'utilisation du header `Authorization` dans les requêtes HTTP...

Actuellement, le seul moyen pour que Robert2 fonctionne malgré tout est de commenter les lignes 60 et 70 du fichier `server/src/App/Services/Auth/JWT.php`...

Il faudrait donc trouver un moyen d'utiliser un custom header à la place (genre `X-Authorization-Token` par exemple ?), ou bien un cookie, ou encore une querystring ? (hum)

Et bien sûr qu'on puisse choisir ceci dans la config de l'application.

**Comment by polosson** [comment]
Hmmm bizarrement, chez Ionos ça semble fonctionner maintenant... étrange ^^ !

**Comment by Donov4n** [comment]
> Hmmm bizarrement, chez Ionos ça semble fonctionner maintenant... étrange ^^ !

On ferme donc ce ticket ?

**Comment by polosson** [comment]
Yes, ça me va !
