### ISSUE TITLE
[Régression] Titre de la page qui disparait

### ISSUE THREAD

**Issue by Donov4n** [Robert-2/Robert2#142]
Suite  à [cette modification](https://github.com/Robert-2/Robert2/commit/77951c767a00094dd4b29bdc140016c51c163ca1#diff-3dffc685a7cdb4d50c1a0835b07dc169f1d0591a86fa27d102125c95d44605e6), les titres des pages disparaissent à certains endroits, notamment lorsqu'il y a plusieurs onglets ...

Voir le screenshot ci-dessous, au changement d'onglet c'est ce que ça donne.

![Capture d’écran 2021-05-08 à 15 46 37](https://user-images.githubusercontent.com/3775007/117541599-e8699480-b014-11eb-9d36-5065d5c1dc23.png)

@polosson je t'assigne le ticket vu que c'est ta modif (et que tu as surement encore la chose en tête vu que ça date de la semaine dernière).

**Comment by polosson** [comment]
Oops !!

Bien vu :grin: 
Je corrige !
