### ISSUE TITLE
A propos du licence Robert2 

### ISSUE THREAD

**Issue by eluos** [Robert-2/Robert2#170]
Pourquoi le code source ou l'application Robert2 n'est pas utilisable commercialement, et se limité seulement dans le cadre de l'usage privé ou personnel ?

Cordialement,
Eluos

**Comment by Donov4n** [comment]
Robert2 peut tout à fait être utilisé __en interne__ dans une entreprise commerciale, le code source peut lui aussi être modifié en interne dans ces entreprises pour leurs besoins spécifiques.

Ce qui n'est pas autorisé avec Robert2, c'est de le re-commercialiser, de quelque manière que ce soit (en standalone ou faisant partie d'un package), en location ou non, en l'ayant modifié ou non, renommé ou non, etc.
Nous nous réservons l'exclusivité de ce type d'activité, sachant que c'est en partie cela qui nous permet de continuer à faire vivre le projet.

Plus d'informations sur la page dédiée sur le wiki: https://robertmanager.org/wiki/licence

**Comment by eluos** [comment]
Alors si je peux utiliser en interne dans mon entreprise, pourquoi je pas le droits de change le titre de l'application et le favicon tout en gardant dans information qui fait référence qui se trouve dans le pied de la page ?

**Comment by eluos** [comment]
Eh oui ce moi ☺️. Alors si vous trouvez cela un peu limite, mieux vaut laisser comme vous l'avez prévu 👌.
