### ISSUE TITLE
[composer migrate] Base table or view not found: 1146 Table 'robert2.inventory_material_units

### ISSUE THREAD

**Issue by Tuxem** [Robert-2/Robert2#196]
Bonjour à la team.

Lors du "composer migrate" j'obtiens l'erreur suivante :

```
== 20210703073402 AddStateToInventoryMaterialUnits: migrating
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'robert2.inventory_material_units' doesn't exist in /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:222
Stack trace:
#0 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(222): PDO->query()
#1 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(238): Phinx\Db\Adapter\PdoAdapter->query()
#2 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(196): Phinx\Db\Adapter\PdoAdapter->fetchAll()
#3 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(196): Phinx\Db\Adapter\AdapterWrapper->fetchAll()
#4 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(230): Phinx\Db\Adapter\AdapterWrapper->fetchAll()
#5 /var/www/Robert2/server/src/database/migrations/20210703073402_add_state_to_inventory_material_units.php(35): Phinx\Migration\AbstractMigration->fetchAll()
#6 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(112): AddStateToInventoryMaterialUnits->up()
#7 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(382): Phinx\Migration\Manager\Environment->executeMigration()
#8 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration()
#9 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#10 /var/www/Robert2/server/src/vendor/symfony/console/Command/Command.php(299): Phinx\Console\Command\Migrate->execute()
#11 /var/www/Robert2/server/src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run()
#12 /var/www/Robert2/server/src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/Robert2/server/src/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#14 /var/www/Robert2/server/src/vendor/symfony/console/Application.php(167): Phinx\Console\PhinxApplication->doRun()
#15 /var/www/Robert2/server/src/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 {main}
Script src/vendor/robmorgan/phinx/bin/phinx --configuration=src/database/phinx.php migrate handling the migrate event returned with error code 1
```

J'imagine qu'il me suffit juste de créer la table dans la BDD et hop mais si vous voulez que je fasse des tests avant n'hésitez pas à me demander ;)

**Comment by polosson** [comment]
Bonjour @Tuxem !

On va regarder ça dès que possible, les migrations qui plantent c'est toujours compliqué. Merci pour le rapport de bug !

**Comment by polosson** [comment]
OK alors moi j'ai une autre erreur, dans la même migration : 

```
PDOException: SQLSTATE[HY000]: General error: 1832 Cannot change column 'state_current': used in a foreign key constraint 'fk_material_units_state_ccurent'
```

Je vais de ce pas faire un correctif et publier la 0.14.1 du coup ^^

**Comment by polosson** [comment]
Alors, je n'ai pas pu reproduire le bug que tu as trouvé @Tuxem, ni en local ni ailleurs. Est-ce que tu aurais modifié la BDD à la main, ou bien lancé des migrations en étant basé sur la branche `develop` à un moment donné ces dernières semaines ?

Cela ressemble à une migration qui n'aurait pas été complétée, mais si Phinx (le système de migration) ne dit rien avant la dernière, c'est qu'elles ne sont pas à jour malgré les apparences... Mais dans le doute, que donne la sortie de la commande `composer migration-status` ?

Sinon, ce qu'il faudrait faire je pense, c'est reprendre une sauvegarde SQL qui date de avant le lancement des migrations, puis relancer la commande `composer migrate` en utilisant la version 0.14.1 (sortie tout à l'heure) ou en checkout sur `master`... Mais encore faut-il avoir fait une sauvegarde ! (ce qui en général est une bonne idée :grin:)

**Comment by polosson** [comment]
Ah ! Mais en regardant de plus près le log de l'erreur, je vois que le souci viens du `fetchAll`... Est-ce que par hasard tu n'utiliserait pas des préfixes de table ? :innocent:

**Comment by Faster01** [comment]
Bonjour à vous, 
J'ai le même soucis que Tuxem mais je n'utilise aucun préfixe dans la BDD.

La version précédente installée était la  0.13.2
Je joins les codes erreur que j'obtient ainsi que la liste des migrations.


Phinx by CakePHP - https://phinx.org.

using config file /home/andorphi/domains/andorphine.be/public_html/location/src/database/phinx.php
using config parser php
using migration paths 
 - /home/andorphi/domains/andorphine.be/public_html/location/src/database/migrations
using seed paths 
warning no environment specified, defaulting to: development
using database andorphi_robert
using table prefix 
ordering by creation time

 == 20210703073402 AddStateToInventoryMaterialUnits: migrating
PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'state_previous' in /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:194
Stack trace:
#0 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(194): PDO->exec('ALTER TABLE `in...')
#1 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(112): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `in...')
#2 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(620): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `in...', Array)
#3 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(995): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('inventory_mater...', Object(Phinx\Db\Util\AlterInstructions))
#4 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#5 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(434): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#6 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#7 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TablePrefixAdapter.php(495): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#8 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(153): Phinx\Db\Adapter\TablePrefixAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#9 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TablePrefixAdapter))
#10 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(629): Phinx\Db\Table->executeActions(true)
#11 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(688): Phinx\Db\Table->update()
#12 /home/andorphi/domains/andorphine.be/public_html/location/src/database/migrations/20210703073402_add_state_to_inventory_material_units.php(32): Phinx\Db\Table->save()
#13 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(112): AddStateToInventoryMaterialUnits->up()
#14 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(382): Phinx\Migration\Manager\Environment->executeMigration(Object(AddStateToInventoryMaterialUnits), 'up', false)
#15 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('development', Object(AddStateToInventoryMaterialUnits), 'up', false)
#16 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('development', 20210703073402, false)
#17 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/symfony/console/Command/Command.php(299): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#18 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#19 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#20 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#21 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(239): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#22 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(117): Phinx\Wrapper\TextWrapper->executeRun(Array)
#23 [internal function]: Phinx\Wrapper\TextWrapper->getMigrate()
#24 /home/andorphi/domains/andorphine.be/public_html/location/src/install/Install.php(234): call_user_func(Array)
#25 /home/andorphi/domains/andorphine.be/public_html/location/src/install/Install.php(114): Robert2\Install\Install::_executePhinxCommand('migrate')
#26 /home/andorphi/domains/andorphine.be/public_html/location/src/App/Controllers/SetupController.php(77): Robert2\Install\Install::createMissingTables()
#27 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Robert2\API\Controllers\SetupController->index(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#28 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#29 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#30 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#31 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#32 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#33 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(68): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#34 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\BodyParsingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#35 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#36 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#37 /home/andorphi/domains/andorphine.be/public_html/location/src/App/Middlewares/Acl.php(22): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#38 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\Middlewares\Acl->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#39 /home/andorphi/domains/andorphine.be/public_html/location/src/App/Services/Auth.php(36): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#40 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\Services\Auth->middleware(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#41 /home/andorphi/domains/andorphine.be/public_html/location/src/App/Middlewares/Pagination.php(20): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#42 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\Middlewares\Pagination->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#43 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#44 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#45 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/http-cache/src/Cache.php(67): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#46 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\HttpCache\Cache->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#47 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#48 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#49 /home/andorphi/domains/andorphine.be/public_html/location/src/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#50 /home/andorphi/domains/andorphine.be/public_html/location/src/App/App.php(44): Slim\App->run()
#51 /home/andorphi/domains/andorphine.be/public_html/location/src/public/index.php(17): Robert2\API\App->__call('run', Array)
#52 {main}



Liste des migrations :

CreateCountries : Up
CreateTags : Up
CreateUsers : Up
CreateParks : Up
CreateCategories : Up
CreateMaterials : Up
CreateCompanies : Up
CreatePersons : Up
CreateEvents : Up
CreateGroupsOfUsers : Up
CreateTaggables : Up
SubCategoryNullForMaterials : Up
CreateUserSettings : Up
ChangeSubCategoriesUnicityConstraint : Up
AddQuantityToEventsMaterialsPivot : Up
AddInformationsToParks : Up
CreateMaterialAttributes : Up
FixEventsLocationNullability : Up
CreateBills : Up
AddIsDiscountableToMaterials : Up
AddIsBillableToEvents : Up
FixTaggablesPrimaryConstraint : Up
AddReferenceToEvents : Up
RemovesMaterialsSerialNumber : Up
CreateUnitsTables : Up
ChangesMaterialUnitsConstraint : Up
AddParkIdInMaterialUnit : Up
AddAttributesCategoriesRelation : Up
AddDateTypeToAttributes : Up
CreateDocuments : Up
CreateUserRestrictedParks : Up
ChangeMaterialAttributesRelationship : Up
AddCasFieldsToUsers : Up
CreateEstimates : Up
AddReferenceToPersons : Up
AddPositionToEventAssignees : Up
AddPictureToMaterials : Up
AddReferenceToMaterialUnits : Up
AddReturnQuantitiesToEventMaterials : Up
AddIsReturnInventoryDoneToEvents : Up
AddIsArchivedToEvents : Up
CreateInventories : Up
CreateMaterialUnitStates : Up
AddFieldsToMaterialUnits : Up
CreateSettings : Up
AddOwnerToMaterialUnits : Up
CreateInventoriesMaterials : Up
FixEventUserConstraint : Up
AddIsReturnedToEventMaterialUnits : Up
ChangeMaterialUnitStates : Up
**AddStateToInventoryMaterialUnits : Down**

**Comment by polosson** [comment]
Bonjour @Faster01 et merci pour le partage.

Dans votre cas, il s'agit sûrement d'une erreur qui est due à la première (celle de la version 0.14.0). Le problème est que lorsqu'on exécute les migrations plusieurs fois alors que l'une d'entre elles a planté, cela décale l'erreur car une partie de la migration a pu être exécutée, et Phinx tente de la ré-exécuter à nouveau, ce qui provoque une erreur plus tôt dans le stack...

Ce que vous pouvez faire pour régler le problème (en supposant que vous utilisiez bien la version 0.14.1 maintenant), c'est de repartir sur une base de données sauvegardée avant l'exécution de ces migrations, et de recommencer. Si vous n'avez pas de sauvegarde (:astonished:), vous pouvez essayer de mettre en commentaire les lignes 8 à 32 du fichier `src/database/migrations/20210703073402_add_state_to_inventory_material_units.php`, puis relancer les migrations, puis remettre sans les commentaires.

Cheers !

**Comment by Faster01** [comment]
@polosson Merci beaucoup, j'ai toujours un backup avant de faire une MAJ ;) 
Du coup avec la version 0.14.1 tout c'est bien passé lors de la migration.

**Comment by polosson** [comment]
Ok, je considère que ceci a été corrigé dans la version 0.14.1, je ferme donc ce ticket.
