### ISSUE TITLE
Abandonner dependabot ?

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#199]
La dernière salve de PRs du dependabot nous fait nous poser la question de son utilité...

Comme ce n'est pas encore possible de grouper les updates dans une seule PR (voir [ce ticket](https://github.com/dependabot/dependabot-core/issues/1190)), peut-être faudrait-il envisager de changer de bot, pour utiliser [Renovate](https://github.com/renovatebot/renovate) par exemple, qui a l'air pas mal du tout.

Cela dit, avons-nous vraiment besoin d'un tel service ? Étant donné qu'on fait les mises à jour de dépendances manuellement, en vérifiant nous-même la compatibilité de chacune de ces mises à jour, la question se pose. À ce moment-là, il semblerait d'après [cette page](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates#disabling-dependabot-version-updates) qu'il suffise de supprimer le fichier `.github/dependabot.yml` et le tour est joué.

Qu'en penses-tu @Donov4n ?

**Comment by Donov4n** [comment]
Ok pour moi, complètement!
