### ISSUE TITLE
Listings : Scroll sur la liste uniquement

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#20]
Si la hauteur de l'écran le permet, il faudrait faire en sorte que le scroll des listings se limite à la liste elle-même, afin de garder visibles les boutons et les filtres en haut de page.

Mais si l'écran est trop petit (en hauteur), le scroll actuel devrait rester en place.

**Comment by Donov4n** [comment]
Je ferme ce ticket car ce n'est pas réellement un problème en l'état et comme l'interface va être revue bientôt, on avisera sur ce qu'on veut faire des listings à ce moment là.

@polosson Si tu juges que ça mérite discussion, n'hésites pas à rouvrir.
