### ISSUE TITLE
Ajouter un message d'aide concernant les caractéristiques spéciales dans l'édition de matériel.

### ISSUE THREAD

**Issue by GeoffreyOlivier** [Robert-2/Robert2#231]
Bonjour, est-ce voulu de ne pas afficher les caractéristiques spéciales à la création d'un produit ? Car ça nécessite de le créer puis d'éditer le produit pour pouvoir remplir les caractéristiques spéciales.
Merci.

**Comment by GeoffreyOlivier** [comment]
Autant pour moi, il faut choisir une catégorie, il serait peut-être pertinent de le préciser.

**Comment by polosson** [comment]
Hello et merci pour le retour @GeoffreyOlivier !

OK c'est noté, on essaiera de faire ça pour la prochaine version. :+1:
