### ISSUE TITLE
Améliorer le calendrier des techniciens

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#248]
Quelques points à corriger dans la page du calendrier de la vue d'un technicien :

- [x] Essayer de forcer la hauteur des slots à 2 lignes max. avec text-overflow caché (mode ellipsis), pour éviter le chevauchement vertical des slots placés le même jour.
- [x] Ajouter une petite marge à gauche et à droite des slots pour aérer un peu.
- [x] ~~Ajouter une infobulle au survol des slots qui affiche toutes les informations de la plage horaire (nom de l'événement, lieu, dates, poste occupé)~~
- [x] Corriger le problème de mauvaise intégration de la scrollbar dans le flux des cases de la semaine.
- [x] Ajouter la possibilité de double-cliquer sur un slot dans le calendrier pour ouvrir la fenêtre de l'événement associé (ouvert directement sur l'onglet "techniciens").
- [x] Ajouter un bouton "voir le calendrier" dans le listing des techniciens.

**Comment by polosson** [comment]
Bon ça prendrait trop de temps de mettre une infobulle sur les items du calendrier : il faut utiliser un "named slot" pour `vue-simple-calendar`, sauf que ça efface tout le style par défaut, il faut tout se refaire à la main, ça risque d'être long et chiant. Je laisse tomber ^^ !

**Comment by Donov4n** [comment]
> Bon ça prendrait trop de temps de mettre une infobulle sur les items du calendrier : il faut utiliser un "named slot" pour `vue-simple-calendar`, sauf que ça efface tout le style par défaut, il faut tout se refaire à la main, ça risque d'être long et chiant. Je laisse tomber ^^ !

D'accord Polo, merci pour l'investigation 👍 .
