### ISSUE TITLE
Récupérer tous les produits avec leurs disponibilités via l'API

### ISSUE THREAD

**Issue by GeoffreyOlivier** [Robert-2/Robert2#252]
Bonjour, je cherche à savoir s'il y a cette possibilité ou si cela est prévu. Je souhaite pouvoir récupérer tous les produits ainsi que leurs disponibilités, pour ensuite les stocké dans un calendrier de type Google Agenda par exemple, et retrouvé tous mes événements avec les produits associés.

Idéalement, via une route HTTP, actuellement, on peut récupérer tous les produits ou tous les événements, mais pour avoir les deux ensemble, on doit interroger une route par matériel. Si j'ai beaucoup de produits, c'est embêtant de faire autant de requêtes.

Je peux peut-être éventuellement, proposer un pull request.

Merci.

**Comment by polosson** [comment]
Bonjour @GeoffreyOlivier !

En effet cette route d'API n'existe pas, car elle ne nous a pas semblé utile jusqu'à présent. Mais si vous en avez besoin, c'est qu'elle doit l'être ! Nous n'aurons malheureusement pas les resources nécessaire à son implémentation, donc si vous voulez proposer une PR, c'est avec plaisir que nous l'intégrerons (après review bien sûr) dans l'application.

Cela dit, une telle route d'API risque de déclencher des requêtes SQL assez lourdes (selon le nombre de matériel et d'événements présents dans la base), et donc d'être potentiellement très longues, voir même de ralentir le serveur... Il faudra garder cela en tête, et pourquoi pas proposer des filtres par défaut (par exemple en ne récupérant que les événements futurs pour chaque matériel)...

Merci pour la proposition en tout cas, on reste en contact !
Cheers

**Comment by GeoffreyOlivier** [comment]
Merci pour votre réponse, c'est avec plaisir que je vais essayer de vous proposer une Pull Request.
Je note également votre suggestion de récupérer uniquement les événements futurs.

Merci.
