### ISSUE TITLE
Problèmes avec les calculs de remise (devis & factures)

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#253]
Il ne devrait pas être possible d'appliquer une remise (ni en % ni avec un montant) si le "total remisable" est égal à zéro.

Voir dans les components `EventBilling` et `EventOverview` : on a une division par 0 qui apparaît !

Pour bien faire, il faudrait même carrément ne pas laisser la possibilité à l'utilisateur de spécifier une remise si on sait déjà que c'est inutile (quand le total remisable est nul, donc).

**Comment by Donov4n** [comment]
Le code a été corrigé pour empêcher la division par zéro etc. mais il faut quand même améliorer ça en supprimant purement et simplement la possibilité d'ajouter une remise pour les events dont aucun matériel n'est remisable.

On devrait sans doute aussi ajouter un message à l'attention de l'utilisateur pour lui expliquer pourquoi il ne peut pas aller plus haut que tant de pourcent pour la remise, du genre: "Vous ne pouvez appliquer qu'au maximum XX% de remise sur cet événement car certain matériel ne sont pas marqués comme remisables." (evidemment, il ne faut pas afficher ça si tout le matos est remisable)
