### ISSUE TITLE
API REST 

### ISSUE THREAD

**Issue by GeoffreyOlivier** [Robert-2/Robert2#263]
Bonjour, je ne sais pas si le sujet a déjà été évoqué, mais pour notre projet, on communique beaucoup avec l'outil Robert. Pour l'instant j'effectue une authentification classique avec identifier et mot de passe, je stocke le token et l'envoie dans l'header de la requête.
La question est, est qu'il y a un moyen plus simple .  Est-il prévu de faire des clés privées et publiques pour l'authentification ?

Merci.

**Comment by polosson** [comment]
Bonjour @GeoffreyOlivier !
Il n'est actuellement pas prévu d'implémenter ceci de notre côté, nous n'avons pas du tout envisagé Robert2 comme une API REST publique.
Cela dit, cette discussion aurait plus sa place sur [le forum du projet](https://forum.robertmanager.org/), si vous voulez bien ouvrir une discussion là bas pour en parler, plutôt ? Merci d'avance (je ferme ce ticket en attendant) :slightly_smiling_face:
