### ISSUE TITLE
Problème de migration vers 0.15.0

### ISSUE THREAD

**Issue by adamlarat** [Robert-2/Robert2#287]
Salut @polosson et @Donov4n !!! Chuis de retour. Bon ok, j'ai pris de GRAAAANNNNDE vacances ;-)
Du coup, bah j'ai perdu le fil du développement, je veux mettre à jour l'appli et paf, ça coince ! 
J'ai suivi la procédure de mise-à-jour stipulée dans la doc, à savoir : 
- faire un backup de la DB
- mettre à jour le répo git (tag: 0.15.0)
- composer install et migrate
- supprimer le fichier `src/var/cache/routes.php` et vérifier l'intégrité du fichier de config `src/App/Config/settings.json`

Et j'obtiens une page blanche avec un 'Robert2' moche au-dessus d'une bande noire avec une icône "je réfléchis" qui tourne en rond à l'infini. 

Du coup je suis revenu en arrière et j'ai testé un peu tous les commits du 'log'. Jusqu'au commit `dd90f4573a226c1a4285bbbc3353d654051120bc` (tag: 0.14.3) ça se passe bien. 

Mais, si je 

- checkout au commit suivant, le `a95ae16bc406bb17aa69d6a884b3a1456c245b42` 
- composer install et migrate
- supprime `src/var/cache/routes.php`

J'arrive sur la page cheloo qui réfléchit avec la bande noire. 
Si je ne supprime pas le fichier de `src/var/cache/routes.php` alors en visitant la racine de l'appli je suis redirigé sur la page `login` avec l'erreur : 
```
The page isn’t redirecting properly

An error occurred during a connection to ****.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

Pareil aux commits suivant. 

Enfin, si je reviens en arrière, soit : 

- git checkout dd90f4573a226c1a4285bbbc3353d654051120bc # tag: 0.14.3
- `sudo -u www-data php composer.phar install; sudo -u www-data php composer.phar install; rm src/var/cache/routes.php`

l'appli marche à peu près avec une erreur de requête SQL concernant `event_assignees` qui a changé de nom en `event_technicians` si j'ai bien compris. Pour rétablir un comportement normal, j'ai rien de mieux à faire que de droper totalement la DB, la recréer et la remplir avec mon fichier de backup, puis relancer une migration. 

Une idée ? 

@+ 
Adam

**Comment by polosson** [comment]
Hello @adamlarat,

Quel est le contenu de tes fichiers `/server/.env` et `/client/.env.development.local` ? (Voir ici [cette section du fichier Contributing](https://github.com/Robert-2/Robert2/blob/master/CONTRIBUTING.md#url-de-lapi-en-d%C3%A9veloppement) pour plus d'infos).

Aussi, il se peut qu'il faille lancer la commande `cd client && npm run build` pour créer un build des sources front-end, quand on installe avec la méthode Git... En effet, nous avons enlevé le build de l'historique Git depuis la dernière version (je vais d'ailleurs mettre à jour la doc de l'installation de ce pas).

Et sinon, pour ce genre de souci (quand ce n'est pas vraiment un bug avéré), il serait préférable d'utiliser [le forum](https://forum.robertmanager.org/) je pense, qui est plus fait pour ça. Merci Adam ! :slightly_smiling_face:

**Comment by polosson** [comment]
Voilà, j'ai mis à jour la doc sur le site concernant la mise à jour de l'appli via Git. C'est par ici : https://robertmanager.org/wiki/update#update-git

@adamlarat dis nous si tu as toujours un souci en suivant ces nouveaux points :) Cheers !

**Comment by adamlarat** [comment]
C'était bien le build client qui manquait, merci ! 
Concernant le forum, je me suis posé la question et puis j'étais dans une réflexion tellement technique que je suis venu ici… T'as raison, ça n'a rien à foutre dans les issues. Désolé, j'y penserai la prochaine fois !
