### ISSUE TITLE
Récupérer images / file_get_contents

### ISSUE THREAD

**Issue by GeoffreyOlivier** [Robert-2/Robert2#289]
Tout d'abord désoler d'avoir mis ce sujet sur le forum, j'avais oublié qu'il faillait parler de développement uniquement sur Github. Je copie donc mon message ici.

Bonjour, je travaille sur un plugin qui récupère les produits de Robert², sauf que depuis quelques jours, ma méthode, qui récupère les images, ne fonctionne plus correctement.

J'ai trouvé la cause après plusieurs recherche, il faut être connecté pour pouvoir avoir accès au fichier, mais même avec un token dans le header je n'arrive pas à accéder aux images.
Je voulais savoir, si vous saviez pourquoi ?

J'ai utilisé Curl, sans résultat puis avec file_get_contents et stream_context_create, aucun résultat positif non plus.

Merci.

**Comment by Donov4n** [comment]
Bonjour Jeff,

Le forum était le bon endroit pour cette demande.   

Mais même sur le forum, nous répondons lorsque nous pouvons, avec en priorité les demandes d'aide à l'utilisation de Robert2.  
Nous ne pouvons malheureusement pas effectuer de support au développement pour des projets tiers de manière "prioritaire", sauf à passer par un rendez-vous avec un développeur Robert2, mais ce service est payant.

Quoi qu'il en soit, et parce que ça m'embête de ne pas répondre du tout :) .... Pour vous aider il nous faudrait plus de contexte, voir même le code utilisé  si possible (en enlevant les données sensibles bien sûr). 

Mais tout ceci, sur [le sujet que vous avez ouvert sur le forum que je viens de restaurer](https://forum.robertmanager.org/d/223-recuperer-images-file-get-contents), je vais fermer ce ticket.
