### ISSUE TITLE
Impossible d'assigner un technicien à un événement

### ISSUE THREAD

**Issue by mrgeek55** [Robert-2/Robert2#294]
Il m'est impossible d'attribuer un technicien à un événement. Le calendrier s'ouvre, je double-clique sur la ligne d'un technicien à l'heure de début voulue pour l'assigner à l'événement. La modal s'ouvre, je choisis le jour/heure de début et de fin, clique sur le bouton "assigner", la modale reste ouverte et mon technicien n'est pas assigné.

Voici l'erreur retournée par la console :

```
error: {
  success: false,
  code: 400,
  message: "Validation failed. See error[details] for more informations.",
  details: {
    0: "",
    1: "SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2021-10-12T09:30:00+02:00' for column 'start_time' at row 1 (SQL: insert into `event_technicians` (`event_id`, `technician_id`, `start_time`, `end_time`, `position`) values (160, 2, 2021-10-12T09:30:00+02:00, 2021-10-12T12:30:00+02:00, Cadreur))"
  },
}
```

Dans PHPinfo voici la config "date":

```
date/time support	enabled
timelib version	2018.03
"Olson" Timezone Database Version	2019.3
Timezone Database	internal
Default timezone	UTC
```

Mon instance de Robert2 tourne sous MAMP 5.7, PHP7.4.2 et MySQL 5.7.26.

**Comment by LaplancheMaxime** [comment]
Bonjour, je viens d'installer Robert2, j'ai exactement le même problème.
