### ISSUE TITLE
Avoir une section de consommables

### ISSUE THREAD

**Issue by josephcab** [Robert-2/Robert2#299]
Cette section permettrait de prendre en compte du matériel qui est plutôt vendu que loué (pièces de rechange, gaffeur, piles, etc.). 
Ce matériel serait donc non remisable, sauf s'il est rendu, évidemment.

J'en profite pour vous remercier du travail fait, et souhaiterais y participer (développement), mais ne sais pas trop comment me lancer (trouver quelque chose de pas trop compliqué pour commencer, et pour ne pas me perdre dans le code).

**Comment by polosson** [comment]
Merci @josephcab pour votre implication !

Ce ticket est un duplicata du #125 à priori, je vais donc le fermer.

Pour votre proposition de dev sur le projet, ça serait avec plaisir mais nous pensons qu'il y a plusieurs freins à votre participation directe :
- Le projet est actuellement dans une phase de refactoring / restructuration du code sur beaucoup de points techniques précis, la période n'est donc pas idéale pour votre apprentissage du stack et des patterns utilisés.
- L'interface va bientôt être complètement révisé, ce qui fait qu'il va être compliqué d'introduire de nouvelles fonctionnalités dans l'application ces prochaines semaines.
- Nous n'avons malheureusement pas le temps de vous aider comme nous aimerions le faire pour prendre en main le code.

Merci encore pour la proposition en tout cas !
