### ISSUE TITLE
Augmenter la taille du champ "lieu" des événements

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#300]
Voir cette discussion sur le forum : https://forum.robertmanager.org/d/246-limitation-caractere-champs-lieu

**Comment by Donov4n** [comment]
J'en ai profité pour changer l'ouverture des adresses : J'ai remplacé OpenStreetMap par Google Maps.

En effet, force est de constater que Google Maps est plus largement utilisé et surtout il semble que la recherche de OpenStreetMap soit pas au niveau de celle de Google Maps (p. exemple : L'adresse que Matthieu a transmis n'était pas résolu sous OpenStreetMap).

**Comment by Donov4n** [comment]
Si jamais, je vais le passer en `TEXT` en gardant un `input[type=text]`
