### ISSUE TITLE
Nom de la catégorie remplacé par "Autre matériel"

### ISSUE THREAD

**Issue by Tuxem** [Robert-2/Robert2#319]
Bonjour à tous,

Mise à jour vers la 0.17.

J'ai voulu tester l'affichage des catégories lors de l'impression de la liste. J'ai bien mes items qui sont triés par catégorie, mais l'intitulé de chaques catégories est "Autre matériel".

J'ai que des catégories. Je n'ai pas de sous-catégories

Est-ce normal ?

En tout cas, encore merci, super taf

**Comment by polosson** [comment]
En effet, en l'absence de sous-catégorie, le système affiche "autre matériel"... Mais cela ne fait sens que quand il existe des sous-catégories à afficher.

Il est possible de supprimer cette mention "Autre matériel" dans le template du PDF, ça se trouve à la ligne 139 de `src/views/pdf/event-summary-default.twig`.

Cela dit, on pourrait ajouter un check qui ajoute cette mention uniquement s'il existe plusieurs sous-catégories différentes dans la liste... À voir.

**Comment by Tuxem** [comment]
Okay, du coup je fais un peu de clean dans mon inventaire et rajoute des sous catégories, ça fera pas de mal ^^

Par contre chose assez étonante, en regardant le twig, il aurait du me mettre "Ma categorie - Autre matériel" alors que là il me méttait juste "Autre matériel". Et maintenant que j'ai mes sous-catégories, il me met juste le nom des sous-catgories.

Du coup c'est pas vraiment un problème mais plus une info donc si vous voulez on peut cloturer l'issue

**Comment by polosson** [comment]
Ah, je pense savoir pourquoi ça se comporte ainsi : c'est parce que le tri est basé sur les sous-catégories directement.

Tu peux essayer de choisir "catégories" dans la page des paramètres globaux de l'appli, sous l'onglet "Fiches de sorties", le sélecteur "Mode de présentation", pour voir ce que ça donne ? Je pense que ça correspondrait plus à ta façon d'organiser le matériel du coup... Dis moi !

**Comment by Tuxem** [comment]
C'était déjà le paramètre sur lequel j'étais. J'ai essayé les deux, ça ne me met que la sous-catégorie, pas de catégorie

**Comment by polosson** [comment]
Hmmm bizarre, il y a donc sûrement un bug à ce niveau là, on va devoir creuser. Merci @Tuxem !

**Comment by Tuxem** [comment]
Comme d'habitude, si vous avez besoin de mon dump SQL ou autre chose n'hésitez pas ;)
