### ISSUE TITLE
Liste du materiel : Tri sur les quantités restantes à date ne fonctionne pas

### ISSUE THREAD

**Issue by Donov4n** [Robert-2/Robert2#324]
Si, dans la page de listing du matériel, on sélectionne une date ou une période (pour avoir les quantités à date) et que l'on tri  (ASC / DESC) sur la colonne "Qté restante", le tri ne s'effectue pas sur les "Quantité restantes" mais sur les quantités en stock. 

En effet, la requête qui part est `ascending=1&orderBy=stock_quantity&dateForQuantities=[DATE]`.  

=> Le back-end devrait partir du principe que si `orderBy` === `stock_quantity` et qu'on a une / des valeur(s) pour `dateForQuantities`, alors c'est sur les quantités restantes qu'il faut trier.  
=> Ou alors le `orderBy` devrait être modifié côté front pour passer par exemple `orderBy=remainingQuantity`

**Comment by polosson** [comment]
Problème : à cause du fait que le tri se fait côté serveur et qu'il a une pagination, l'implémentation de ceci serait très complexe et pourrait impacter les performances.

Par contre on peut faire en sorte que le tri ne puisse pas être fait sur la colonne "qté restante" depuis l'UI.
