### ISSUE TITLE
Fiche de sortie : Ajouter un texte personnalisé de conditions générales ou autre en fin de PDF

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#33]
Demande initiale : Intégrer les conditions du prêt au verso de la feuille de prêt (ou une page supplémentaire).

On pourrait aussi permettre d'afficher ce texte sur les devis quand ils seront implémentés. Par exemple, en donnant le choix "Devis" / "Fiche de sortie" / "Les deux" lors de la sauvegarde.

**Comment by Donov4n** [comment]
Ce ticket ne semble plus vraiment d'actualité car la fonctionnalité a été implémentée.  

Quoi qu'il en soit, la deuxième partie, qui dit qu'on devrait pouvoir afficher du texte personnalisé aussi dans les devis (et éventuellement factures), elle, n'a pas été implémentée en même temps que les devis. / facture.

Il faut qu'on corrige ça car c'est typiquement sur ces fichiers que l'on veut du texte personnalisé ...

**Comment by Donov4n** [comment]
Je ferme celui-ci, ça se passe maintenant dans le #352.
