### ISSUE TITLE
Améliorer le message d'erreur de duplication d'événement

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#346]
Quand on veut dupliquer un événement, si une erreur survient, parce que le technicien est déjà pris pendant la nouvelle période par exemple, on a pas d'explication précise pour palier au problème, juste un message obscur du genre *"Request failed with status code 400"*...

De plus, un événement est bien créé malgré le fait qu'une erreur soit affichée (et la fenêtre qui reste ouverte), mais on ne le sait que quand on ferme la fenêtre et que le calendrier est rafraîchi.

![Screenshot_20220321_093000](https://user-images.githubusercontent.com/1675719/159228040-e37675dc-d79c-4ca1-a3a1-7b52d35595d1.jpg)

Il faudrait implémenter une meilleure gestion des erreurs, aussi bien côté API que côté front-end.

C'est aussi lié au #347 qui pourrait améliorer grandement l'UX de cette feature.

**Comment by Donov4n** [comment]
@polosson Qu'est ce qu'on fait pour ce souci ?

On bloque la duplication complétement ? On duplique en supprimant le technicien assigné ? On demande une confirmation à l'utilisateur de confirmer la création si on constate que des techniciens ne pourront pas être mobilisés dans le nouvel événement vu qu'ils le sont déjà à cette période ?

**Comment by polosson** [comment]
Hello @Donov4n,

Dans l'idéal, il faudrait que l'utilisateur sache qu'il y a un problème yes, et qu'il puisse choisir de ne pas continuer, ou de continuer en tout connaissance de cause (technicien qui ne sera pas assigné). On pourrait également bloquer la duplication sans autre, en expliquant pourquoi c'est bloqué, mais l'user ne pourra pas vraiment régler la situation tout seul, car enlever le technicien de l'événement original c'est pas terrible, et enlever le technicien de l'événement où il est déjà assigné (celui qui crée le conflit), ça l'est encore moins.

Tu crois qu'on peut faire le truc en deux temps du coup, en ajoutant un paramètre dans la requête de la duplication pour ne pas dupliquer le technicien si l'utilisateur choisis "OK" ? On pourrait aussi afficher à l'avance le problème (au moment où l'user choisis les dates du futur événement), avec un message du genre "le technicien X ne pourra pas être assigné au nouvel événement", mais ça implique de faire une requête pour aller chercher les events contemporains et faire un check.
