### ISSUE TITLE
Support Robert2/Loxya sur Docker

### ISSUE THREAD

**Issue by LaplancheMaxime** [Robert-2/Robert2#351]
Bonjour, 

Dans le cadre d'un besoin personnel, j'ai créé une image Docker Robert2/Loxya.
Si jamais ça peut servir à quelqu'un : 

- [Repo gitlab](https://gitlab.com/mlaplanche/docker-robert2)
- [Repo Github (miroir)](https://github.com/LaplancheMaxime/docker-robert2)

Excellente journée à vous, merci pour le travail, super outil 👍

**Comment by Donov4n** [comment]
Merci encore pour la contribution, je ferme ce ticket ! :)
