### ISSUE TITLE
[Regression ?] Les assignations des techniciens dans les événements ne suivent pas l'update des dates de celui-ci

### ISSUE THREAD

**Issue by Donov4n** [Robert-2/Robert2#357]
Sur la démo publique j'ai constaté, dans le récap en fin d'event, que les dates d'assignations des techniciens n'étaient pas raccord avec les dates de l'événement lui-même.

Il faudrait checker s'il n'y a pas eu de régression à ce niveau.  
Les dates d'assignation des techniciens devraient "suivre" les dates de l'événement et ne devraient pas pouvoir se retrouver hors de celles-ci.

**Comment by polosson** [comment]
Alors après plein d'essais dans tous les sens, je n'ai pas réussi à reproduire le problème...

Je soupçonne le script de reset de la démo qui doit être incomplet... Je vais vérifier ça.

Mais si quelqu'un tombe sur le problème après avoir fait une manipulation précise, merci de nous en faire part afin qu'on puisse le corriger !

**Comment by polosson** [comment]
Okay !! Je confirme, le problème venait bien du script de reset des données qui est lancé tous les matins à 5:00. Les assignations des techniciens n'étaient pas mises à jour avec celles des événements, un oubli de ma part. Donc le code de l'application va bien pour cette feature ! :sweat_smile: Je ferme ce ticket.
