### ISSUE TITLE
Problème fonctionnement lien d'abonnement externe

### ISSUE THREAD

**Issue by LaplancheMaxime** [Robert-2/Robert2#360]
Bonjour,
 
Je rencontre des difficultés à l'utilisation du lien d'abonnement externe du calendrier. 

1. Est-il possible d'ajouter une correction de fuseau horaire globale du fichier ics ? 
2. J'ai d'abord essayé d'importer le fichier sur Google Agenda, celui-ci n'importe aucun élément. (0 sur 4 événements, aucun message d'erreur). Et donc dès que j'active l'abonnement par URL, aucun événement n'est ajouté... Sur Outlook, les événements s'ajoutent. Mais aucune mise à jour malgré des mises à jour manuelles (je l'ai laissé en import, voir s'il y a une tempo avec du cache côté Microsoft...)
3. Le lien généré par l'application ne tient pas compte du SSL, malgré que l'option ait été activée lors de l’installation

Je reste à disposition si vous avez besoin de plus d'informations.

cc: @Donov4n @polosson

**Comment by Donov4n** [comment]
Bonjour @LaplancheMaxime et merci pour l'interêt que vous portez à Loxya / Robert2.

Concernant les points que vous mentionnez:

1. Normalement le fichier ICS contient déjà les informations de fuseau horaire.
    Les informations de date, dans le fichier, sont spécifiés dans le fuseau horaire utilisé par votre configuration de PHP.
    Libre ensuite à votre client de calendrier de vous l'afficher selon votre configuration dans celui-ci.
    (on lui passe toute les infos pour qu'il sache dans quel fuseau horaires les dates et heures sont spécifiées).

   Reste que je ne suis pas certain d'avoir compris votre question, si vous pouvez précisez (si je n'y ai pas déjà répondu) ?

2. C'est bizarre, en effet. Il faudrait nous fournir une copie (même anonymisée) du fichier ICS problématique pour qu'on puisse voir s'il y a effectivement un souci avec celui-ci.
    Quelques points à noter toutefois:  
    - Seuls les événements qui ne sont pas archivés et qui datent de moins de 3 mois sont récupérés.
    - Les providers (Google Agenda, Outlook) font un peu ce qu'ils veulent en terme de rafraichissement. Google ne le fait toutes les 24h et ce n'est pas configurable (par exemple, cf). 

3. Concernant le SSL, je n'ai pas pu reproduire le souci, le lien généré chez moi est bien servi en `https://(...)`.  
    Si ce n'est pas le cas chez-vous, veuillez vérifier les éléments suivants dans votre le fichier `src/App/Config/settings.json`:
    - La valeur de `apiUrl` commence bien par `https://`.
    - La valeur de `useHTTPS` est bien `true`.

**Comment by LaplancheMaxime** [comment]
Bonjour,

1. Concernant le fuseau horaire, je n'ai pas fait attention à ma configuration de PHP. Je pense effectivement que je peux ajuster le paramètre dans la configuration de PHP. Je pensais à des utilisateurs moins avertis : peut être mettre un paramètre permettant de spécifier le fuseau horaire ?
Vous avez bien répondu à ma question, merci 👍 

2. Voici un fichier ics : 
[1bd02748-edd1-4ec0-895d-7cbfc27d75d8.ics.zip](https://github.com/Robert-2/Robert2/files/8865736/1bd02748-edd1-4ec0-895d-7cbfc27d75d8.ics.zip)
J'ai essayé de l'importer en fichier plat dans un calendrier existant de Google Agenda : il n'importe aucun événement.

3. C'est étrange, le settings.json est correct.

Merci pour votre réactivité 👍

**Comment by Donov4n** [comment]
1. Concernant le fuseau horaire, j'ai créé un ticket pour la personnalisation in-app (#361), ça me semble en effet être une bonne idée de proposer ça à terme. 

2. Après vérification, __il y a en effet un problème avec le champ UID__ dans Google Calendar.  
    Ce champ devrait être unique "globalement" (cf. [la rfc](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.4.7)). 
    __(Quand je dis "globalement" unique ça veut dire vraiment globalement, pas simplement dans ce fichier)__. 
    
    Il va falloir sans doute opter pour un format du genre `md5([domaine de Robert2 / Loxya])/[Id de l'event]`.  
    Reste à savoir ou on va chercher l'info du "Domaine de Robert2 / Loxya, en l'état, la config. `apiUrl` semble être pas mal.

    => À fixer dans la 0.19.0.

3. Alors c'est vraiment bizarre :)   
    À voir si vider votre cache change quelque chose, mais normalement le système se base sur l'apiUrl donc...
    Pour aller plus loin, il faudrait vérifier la requêtes fetch qui est effectuée depuis la page des paramètres du calendrier (GET /api/settings):  
    - Vérifier que la Request URL est bien en https: (`https://()/api/settings`)
    - Vérifier la valeur de `calendar.public.url` dans la réponse, si ça commence par `https://` (ou non).

**Comment by LaplancheMaxime** [comment]
Merci pour votre retour!

Concernant le retour de /api/settings : 
  - L'url est en http (cache vidé)
