### ISSUE TITLE
Date invalide empêche d'imprimer la liste d'un parc

### ISSUE THREAD

**Issue by denis-bg** [Robert-2/Robert2#365]
Problème mineur : une caractéristique spéciale de type Date qui a été renseignée pour un matériel puis effacée génère une erreur "Invalid date" sur l'onglet Informations de la fiche du matériel.

Problème majeur : lorsqu'on essaie d'imprimer la liste du parc correspondant on obtient une erreur 500 : 
`error :	`
`code :	500`
`message	: "An exception has been thrown during the rendering of a template (\"DateTime::__construct(): Failed to parse time string (Invalid date) at position 0 (I): The timezone could not be found in the database\")."`
`debug : 	`
`file : 	"/var/www/baron-guibal/releases/0.18.1-premium/src/views/blocks/materials/attribute.twig, line 6."`

**Comment by polosson** [comment]
Merci @denis-bg ! Cela a déjà été corrigé :innocent: Ce bug ne sera donc plus présent dans la prochaine version (0.19), qui devrait sortir dans pas très longtemps...

Cheers !
