### ISSUE TITLE
Installation : création du premier utilisateur admin buggée

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#367]
Quand on crée le premier utilisateur admin à l'étape 8 du wizard d'installation, le mot de passe est stocké en clair (:O) dans la base, et le profile et les settings associés à l'utilisateur ne sont pas créés.

**Comment by Donov4n** [comment]
Sauf erreur ce ticket aurait dû être fermé en même temps que la release de la 0.19.2, je le ferme donc.
