### ISSUE TITLE
La copie de l'URL du calendrier public ne fonctionne pas

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#369]
Quand on clique sur le bouton "copier" à droite du champ qui affiche l'URL du calendrier public, cela vide le presse-papier au lieu de le remplir avec l'URL.

**Comment by Donov4n** [comment]
Bizarre, ça fonctionnait avant. En tout cas sur Chrome.

**Comment by Donov4n** [comment]
Corrigé dans premium, sera backporté lors du prochain merge Premium => OSS.
