### ISSUE TITLE
Récupération de l'image d'un matériel via API

### ISSUE THREAD

**Issue by LaplancheMaxime** [Robert-2/Robert2#370]
Bonjour, 

Je viens de constater que le endpoint pour récupérer la photo d'un matériel n'a pas le préfixe "/api/".

Exemple: 

- Endpoint pour récupérer les tags d'un matériel : "/api/materials/ID/tags"
- Endpoint pour récupérer l'image d'un matériel : "/materials/ID/picture" 

C'est volontaire ?

Merci pour le travail !

**Comment by Donov4n** [comment]
Bonjour @LaplancheMaxime,

La route `/materials/[ID]/picture` n'est pas une route d'API (dans le sens ou on l'entend (= REST-like)) comme l'est celle de la récupération des tags.  
Cette route représente l'URL "publique" de l'image liée à un matériel, elle retourne le fichier "brut" (et non un payload JSON), elle est d'ailleurs principalement utilisée en valeur de l'attribut `src` dans des balises `<img />`.

Théoriquement, c'est d'ailleurs l'URL qui devrait être retournée par la clé `picture` du payload de `/api/materials/[ID]`.  
(Plutôt que le nom du fichier raw comme actuellement, avec pourquoi pas un sous-object avec les différentes tailles lorsqu'on aura implémenté ça, si besoin)

En espérant avoir pu répondre à votre question,

Merci pour l'intérêt pour Robert2 (et pour l'initiative liée à Docker !!)

**Comment by LaplancheMaxime** [comment]
Effectivement c'est plus clair, merci pour les infos! Je vais m'adapter. 

Si besoin je peux créer un ticket pour la clé picture. 

Pas de souci pour Docker, je l'ai fait pour moi, je me suis dit que ça pouvait servir !
