### ISSUE TITLE
Permettre de définir une durée de location différente de la durée de tarification

### ISSUE THREAD

**Issue by josephcab** [Robert-2/Robert2#372]
Serait-il possible de définir une durée de location (durée d'emprunt du matériel) qui puisse être différente de la durée de tarification (nombre de jours réellement facturés à l'utilisateur).

Cela permettrait d'avoir une facturation uniquement les jours d'usage du matériel, sans compter les jours d'installation et de démontage de ce dernier, généralement non facturés.

Merci d'avance

**Comment by Donov4n** [comment]
Implémenté dans la 0.24.

**Comment by josephcab** [comment]
Merci beaucoup
