### ISSUE TITLE
Facturation d'éléments à l'événement et non au nombre de jours

### ISSUE THREAD

**Issue by josephcab** [Robert-2/Robert2#374]
Objectif : permettre de facturer des frais qui s'appliquent de manière fixe à un événement quelle que soit sa durée.
Par exemple : 

- Le gaffeur prévu pour l'événement
- Les frais kilométriques de transport du matériel
- Les consommables divers
- etc.

**Comment by Donov4n** [comment]
Cette demande semble être un duplicata du ticket #125.  

Si des éléments sont manquants dans le ticket initial, merci de mettre un commentaire dans celui-ci !

**Comment by josephcab** [comment]
Effectivement. Désolé
