### ISSUE TITLE
Fonctionnement anormal : access token expiré

### ISSUE THREAD

**Issue by LaplancheMaxime** [Robert-2/Robert2#383]
Bonjour, 

Lors d'une utilisation de l'application via API, Robert ne renvoi pas d'erreur lorsque le token de l'utilisateur n'est plus valide.
Le contrôleur renvoie une page HTML avec un code valide 2xx. 

Pourriez-vous apporter une correction à ce problème ? 
Merci pour votre travail.

**Comment by polosson** [comment]
Bonjour @LaplancheMaxime, merci pour votre signalement.

Je crois bien que ceci a été corrigé dernièrement, le problème n'apparaîtra plus dans la version 0.20 (qui devrait sortir très bientôt) :slightly_smiling_face:
Cheers !
