### ISSUE TITLE
Texte personnalisé non visible

### ISSUE THREAD

**Issue by josephcab** [Robert-2/Robert2#384]
Le texte personnalisé pour les fiches de sorties n'est plus visible sur ces dernières.

**Comment by polosson** [comment]
Bonjour @josephcab et merci pour votre contribution.

Il nous faudrait plus d'informations, car nous n'avons pas constaté de problème à ce niveau-là, et ne pouvons pas reproduire ce bug potentiel...

Pouvez-vous nous montrer le contenu du texte que vous utilisez ? Quelle taille fait-il (combien de caractères) ? Peut-être qu'un caractère spécial empêche son bon affichage dans le PDF ? Est-ce que le titre, lui, est bien affiché ? Peut-être que quelques captures d'écran pourraient également nous aider à cerner le problème.

Ensuite, il nous faudrait aussi des informations techniques sur le type de serveur que vous utilisez, les versions de PHP et MySQL qui sont installées, etc.

**Comment by josephcab** [comment]
De mon côté, je n'avais pas de soucis jusqu'à la dernière mise à jour de Robert2. 
Le texte personnalisé est bien défini et activé sur l'outil, mais il n'apparait pas sur les PDF. 

Je me demande de ce fait si ce n'est pas la mise à jour qui a rompu un lien ou quelque chose du genre.

Après de multiples tests j'ai fini par constater que ce problème ne se posait que pour les événements créés avant la mise à jour. Les ayant depuis tous été inventoriés, je ne peux plus effectuer de captures d'écran. 

Version PHP : 8.0
Version MySQL : 7.4.33 

Merci pour votre aide

**Comment by Donov4n** [comment]
Bonjour @josephcab,

Pourriez-vous re-tester lorsque vous passerez à la dernière version du logiciel et voir si le souci est encore d'actualité ?  
Car comme dit plus haut, nous n'avons pas réussi à reproduire le problème.

Si d'aventure le bug se produit toujours,de votre côté, il faudra sans doute faire certaines vérification (que l'on pourra éventuellement faire en en call avec partage d'écran si c'est possibl, à voir à ce moment là)

Merci d'avance,

**Comment by polosson** [comment]
Bonjour @josephcab, avez-vous des nouvelles à propos de ce bug potentiel ? :slightly_smiling_face:

**Comment by josephcab** [comment]
J'essaie de faire la mise à jour le WE prochain.

**Comment by Donov4n** [comment]
Faute de réponse depuis presque 2 mois, je ferme le ticket, merci de revenir vers nous si le problème est toujours d'actualité.
