### ISSUE TITLE
Activer CORS à l'install plante l'assistant

### ISSUE THREAD

**Issue by Nakio195** [Robert-2/Robert2#386]
Bonjour à vous deux ! Une fois de plus merci beaucoup pour votre travail efficace et incroyable !

Dans une période d'inventaire et pour préparer la saison je me suis dis qu'il serais temps de passer de la 18 à la 20 ! 
Je lance donc une fresh install depuis la dernière release zippé et décide d'activer CORS car ça fais un moment que je réfléchis à gratter dans l'API depuis une appli compagnonne avec Qt.
Malheureusement dès que les identifiants pour la BDD sont rentrés et que l'on passe à l'étape de migration je tombe sur cet erreur :

```
404 Not Found
The application could not run because of the following error:

Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /home/robert/html/Robert2_20/Robert2/src/App/App.php
Line: 137
Trace
#0 /SEB/Robert2/vendors/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Robert2\API\App->Robert2\API\{closure}()
#1 /SEB/Robert2/vendors/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#2 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#3 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#4 /SEB/Robert2/vendors/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#5 /SEB/Robert2/vendors/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#6 /SEB/Robert2/src/App/Middlewares/BodyParser.php(62): Slim\Routing\RouteRunner->handle()
#7 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(147): Robert2\API\Middlewares\BodyParser->process()
#8 /SEB/Robert2/src/App/Middlewares/Acl.php(35): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#9 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\Middlewares\Acl->__invoke()
#10 /SEB/Robert2/src/App/Services/Auth.php(37): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\Services\Auth->middleware()
#12 /SEB/Robert2/src/App/Middlewares/Pagination.php(20): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\Middlewares\Pagination->__invoke()
#14 /SEB/Robert2/vendors/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /SEB/Robert2/vendors/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /SEB/Robert2/src/App/App.php(74): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(313): Robert2\API\App->Robert2\API\{closure}()
#20 /SEB/Robert2/vendors/slim/http-cache/src/Cache.php(67): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\HttpCache\Cache->process()
#22 /SEB/Robert2/vendors/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /SEB/Robert2/vendors/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#24 /SEB/Robert2/vendors/slim/slim/Slim/App.php(199): Slim\App->handle()
#25 /SEB/Robert2/src/App/App.php(51): Slim\App->run()
#26 /SEB/Robert2/src/public/index.php(17): Robert2\API\App->run()
#27 {main}
```

J'ai vu que dans la stack on passais par la ligne 74@App.php qui correspond à la configuration de CORS 
https://github.com/Robert-2/Robert2/blob/f9f23d628370a967d5d71d81430c3a98c004c4ed/server/src/App/App.php#L74

Une fois désactivé dans le settings.conf on passe à l'étape de migration sans soucis ! 

Bon par contre j'ai des soucis de migrations de DB... C'est une autre histoire.

J'ai bien conscience que CORS n'est surement pas votre priorité mais au moins ça seras noté quelque part ! 

Merci encore pour votre boulot et à bientôt ! 

Théo pour [SEB]

**Comment by Donov4n** [comment]
Bonjour !

Merci pour votre retour !

Pour ce qui est du souci que vous rencontrez avec CORS, pouvez-vous fournir les détails de la requête envoyée et qui renvoie une 404 (méthode, url (uniquement la partie "path"), header (en cachant les données sensibles s'il y en a) etc.)

---

Concernant les soucis de migrations de base de données, étant donné que cette version améliore la structure de la base au niveau des techniciens et bénéficiaires, il se peut que la migration rencontrent des soucis si des erreurs ce sont glissés au fil du temps dans vos tables liés.

À ce sujet, vous pouvez consulter le forum ou nous avons couvert ce type de soucis plusieurs fois récemment: 
- https://forum.robertmanager.org/d/339-erreur-de-migration-des-donnees-vers-v0203/5
- https://forum.robertmanager.org/d/332-mise-a-jour-020-erreur-de-migration

**Comment by Nakio195** [comment]
Bonjour ! Pour la migration c'est effectivement les deux sujets qui m'ont permis de résoudre le problème.

Concernant le problème, je ne fais aucune requêtes pour l'instant c'est bien lors des étapes de l'assistant d'installation que je tombe sur cette erreur.

Pour reproduire l'erreur : 

1. Installe neuve depuis la dernière release zip github 
2. Activer CORS lorsque cela est proposé
3. Après la saisie des infos de la BDD cette erreur apparait et empêche l'accès à l'étape de migration

Pour info je n'ai pas refais cette procédure mais j'essaye dès que j'ai le temps.

**Comment by Donov4n** [comment]
Votre problème survient donc au moment ou la configuration est réellement mise à jour (même si vous remplissez des infos pendant quelques étapes avant d'arriver à l'étape de bdd, ce n'est qu'à ce moment là qu'elles sont réellement persistées en tant que paramètres de l'application).

Ce qui est surprenant c'est que je ne reproduis absolument pas le souci. Il faudrait quand même nous transmettre les données de la requête que votre navigateur envoie au serveur à ce moment là (en ouvrant vos outils de développeur AVANT que le problème se produise et en allant dans l'onglet network, c'est la première requête de la liste), voir l'exemple ci-dessous:

![Capture d’écran 2023-04-20 à 16 59 27](https://user-images.githubusercontent.com/3775007/233406403-25b6642e-885d-4edf-b73c-d1021f71e408.png)

**Comment by Nakio195** [comment]
Voici la requête effectuée par mon navigateur

![image](https://user-images.githubusercontent.com/14911073/233597281-36554f12-dac7-4157-9d57-96d9721e0322.png)

**Comment by Donov4n** [comment]
Merci pour le screenshot. À première vu il n'y a rien de suspect, on a même les CORS d'activés en réponse.

Malheureusement, pour aller plus loin il va sans doute falloir que l'on investigue ensemble le problème, en appel avec partage d'écran. Pour cela, vous pouvez me contacter en privé via le formulaire de contact du site et nous conviendrons d'un RDV pour voir ça ensemble.

**Comment by Donov4n** [comment]
Je viens de me rendre compte de quelque chose:

Le routing semble considérer votre requête comme une requête d'API et renvoie  une 404 car `/install` ne fait pas partie de ce scope.  

N'y aurait-il pas un souci de configure du `apiUrl` dans votre fichier `src/App/Config/settings.json` ?  
La valeur ne doit pas contenir de `/api` à la fin. Il faut aussi vérifier l'URL Rewriting dans votre configuration Apache.

Quoi qu'il en soit, n'hésitez pas à prendre contact avec moi comme dit plus haut.

**Comment by Nakio195** [comment]
Bonjour, pas de /api dans le settings.conf
```
{
    "apiUrl": "https://robert-dev.coucou.fr",
    "enableCORS": true,
    "displayErrorDetails": true,
    "useRouterCache": true,
    "useHTTPS": true,
    "sessionExpireHours": 12,
    "JWTSecret": "b1c09coucou8fa381dad4954b3061",
    "httpAuthHeader": "Authorization",
    "defaultLang": "fr",
    "currency": {
        "symbol": "€",
        "name": "Euro",
        "iso": "EUR",
        "symbol_intl": "€",
        "decimal_digits": 2,
        "rounding": 0
    },
    "billingMode": "partial",
    "degressiveRateFunction": "daysCount",
    "maxItemsPerPage": 100,
    "db": {
        "host": "localhost",
        "username": "coucou",
        "password": "lala",
        "database": "coucou",
        "prefix": ""
    },
    "companyData": {
        "country": "",
        "email": "",
        "legalNumbers": [
            {
                "name": "SIRET",
                "value": ""
            },
            {
                "name": "APE",
                "value": ""
            }
        ],
        "locality": "coucou",
        "logo": null,
        "name": "coucou",
        "phone": "",
        "street": "coucou",
        "vatNumber": "",
        "vatRate": 0,
        "zipCode": "01234"
    }
}
```

Et le Rewrite est bien activé et fonctionnel car j'arrive à réécrire d'autres URL et que la version 20 de Robert fonctionne correctement. 

D'ailleurs sur la version 20 fonctionnelle j'ai tenté de réactiver CORS et impossible d'accéder à la page login (redirections infinies)
![image](https://user-images.githubusercontent.com/14911073/233780815-fa6e1663-8313-49a9-8e55-88cf89a4e60d.png)

Proposition de RDV envoyée :)

Merci encore !

**Comment by Donov4n** [comment]
Pour ce qui est du rendez-vous proposé, vous êtes dans doute passé par le booking d'un rendez-vous téléphonique dédié aux appels commerciaux, je parlais d'envoyer un message via le formulaire de contact. Je vais vous contacter en privé via GitHub.

**Comment by Donov4n** [comment]
Update: Votre profil GitHub ne me permet pas de vous contacter, pouvez-vous passer par le formulaire de contact du site (et non la prise de RDV du coup) ?

**Comment by Donov4n** [comment]
_J'ai tenté de vous contacter via la seule adresse mail que j'ai pu trouver grâce à nos précédents échanges, si vous n'avez rien reçu, merci de passer par le formulaire de contact du site (et non pas la prise de RDV, qui est dédiée aux RDV commerciaux et dont la personne en charge est absente en ce moment). Merci !_

**Comment by Donov4n** [comment]
Après investigation en session de support personnalisé, le problème venait du fait que le cache n'avait pas été vidé lors de la mise à jour ET / OU l'extension OpCache de PHP servait encore une version compilée obsolète des fichiers de l'application.

Pour résoudre le problème il a donc fallu:
-  Vider le cache (supprimer le contenu du dossier `src/var/cache`)
- Redémarrer PHP (pour "vider" le cache de OpCache).
