### ISSUE TITLE
Jeton d'authentification expiré : Téléchargement des images

### ISSUE THREAD

**Issue by LaplancheMaxime** [Robert-2/Robert2#387]
Messieurs, 

Je me permet de refaire un ticket concernant mon ticket #383 
Le souci n'est pas résolu avec la version 20.X

> Actuellement pour récupérer l'image d'un matériel, je passe par l'url publique, avec le jeton d'identification de la session.
> Cependant, lors que le jeton a expiré, j'ai comme retour la page de connexion.
> 
> Est-il possible d'avoir un endpoint sur le contrôleur pour récupérer la photo ?
> Je pense qu'il faut "juste" ajouter la route api/materials/:id/picture, vers getPicture du controller ?

En vous remerciant par avance
Bon courage

**Comment by LaplancheMaxime** [comment]
Bonjour @polosson,
Désolé pour ma réponse tardive. 

Nous utilisons Robert dans son utilisation prévue. Cependant, nous avons un front qui nous permet à nos clients de faire des demandes de location/devis directement depuis celui-ci. Nous mettons également à disposition une liste des matériels disponibles.

Nous utilisons donc l'API de Robert pour les actions suivantes
- `GET - Disponibilités d'un matériel sur une période`
- `GET - Photo d'un matériel`
- `GET - Détails d'un matériel`
- `GET/POST/PUT - Bénéficiaires`
- `GET/POST/PUT - Entreprises`

Nous l'utilisons également pour synchroniser les bénéficiaires de robert vers des tiers facturables dans notre ERP.
Pour réaliser l'ensemble des actions, nous utilisons un utilisateur "API". Nous l'authentifions via le endpoint `POST - /session`

Le contexte est-il plus précis ?

Le problème, c'est lorsque nous tentons de récupérer les photos mais que le jeton est expiré, nous obtenons un retour en HTML, en `HTTP 200`. (La page de login en l’occurrence)
Nous utilisons donc le endpoint`/materials/12/picture` comme prévu.
Est-il possible de passer cet endpoint dans la route `api/`.
Exemple : 
- `_BASE_URL_/api/materials/id/picture` plutôt que `_BASE_URL_/materials/id/picture`

Nous pourrions ainsi profiter du même comportement que tous les autres endpoints ? (404, 404, 200, etc...)

**Comment by polosson** [comment]
Hello @LaplancheMaxime,

Ceci va être corrigé dans la prochaine version (0.24) : les URL des photos de matériel vont devenir "publiques". Il faudra utiliser l'URL `/static/materials/[id]/picture` à la place de `materials/[id]/picture`.

Cette nouvelle route étant publique, vous n'aurez donc plus besoin d'authentification JWT préalable pour récupérer les photos du matériel.

Je ferme ce ticket vu que ce sera très bientôt corrigé :slightly_smiling_face:
