### ISSUE TITLE
Page noire après installation - prérequis de version navigateur?

### ISSUE THREAD

**Issue by benIT** [Robert-2/Robert2#39]
Bonjour,
je viens de procéder à l'installation de la v0.9.1 sur le lan de mon entreprise (apache2) sur une pile : Apache2/php-fpm-7.3/mariaDBv10.3.18

L'application fonctionne parfaitement depuis mon poste linux avec firefox 81.0 (64-bit), en revanche sur le poste windows doté de firefox 52.9.0 (32 bits), la mire de login n’apparaît pas, seul le fond noir est présent.

Il n'y a aucune trace d'erreur dans les journaux apache2.

Après avoir inspecté avec les outils de débogages web (f12 > onglet réseau), je m'aperçois que sur le poste problématique windows, seules 5 requêtes http sont effectuées lors du chargement contre 9 sur le poste linux fonctionnel :

**Linux firefox 81.0 (64-bit) OK: 9 requêtes http au chargement de la page**
![image](https://user-images.githubusercontent.com/2970652/95076901-dfc57e80-0712-11eb-983b-7158b92d63e2.png)

**Windows firefox 52.9.0 (32 bits) KO : 5 requêtes http au chargement de la page**
![image](https://user-images.githubusercontent.com/2970652/95076777-af7de000-0712-11eb-97eb-3db297c4b58e.png)

**Ma question est donc la suivante : y a t il un pré-requis de navigateur/version pour utiliser Robert2 ?** 

En tous les cas, merci pour votre travail !

ben

**Comment by polosson** [comment]
Bonjour @benIT ! En effet, il se peut que les versions les plus anciennes des navigateurs ne soient pas compatible avec l'application Robert2... Cependant, nous n'avons pas encore pu faire le recensement de ces navigateurs, on ne peut donc pas vous dire quelle est la version minimum de Firefox requise pour que tout fonctionne correctement.

Cela dit, si vous avez accès à plusieurs versions différentes de Firefox dans votre entreprise, nous vous serions reconnaissants de faire quelques tests pour nous dire ce qu'il en est. Merci d'avance !! :+1:

**Comment by benIT** [comment]
Bonjour @polosson,
merci pour votre réponse.

Les retours que je peux vous fournir concernant les versions de firefox qui sont disponibles chez nous sont :

- test sur firefox 60.9.0esr (32 bits) : ok
- test sur firefox 52.9.0 (32 bits) : ko

J'ai vu que que la partie frontend s'appuyait sur vue.js, la rubrique [browser compatibility du projet est disponible sous ce lien](https://github.com/vuejs/vue#browser-compatibility). On peut y lire : 

> Vue.js supports all browsers that are ES5-compliant (IE8 and below are not supported).

D'après cette ressource, vue.js indique que la première version de firefox 100% compatible est la 68.

![image](https://user-images.githubusercontent.com/2970652/95296746-9a6f9100-0879-11eb-9851-8200bdf5c22e.png)

Pour ma part, voyant que l'appli semble fonctionner (à tester plus en profondeur) sur  firefox 60.9.0, je pense qu'ils serait intéressant de tester dès [firefox quantum (soit version 57)](https://fr.wikipedia.org/wiki/Historique_des_versions_de_Mozilla_Firefox) pour se prononcer plus précisément.

**Comment by Donov4n** [comment]
La liste des navigateurs supportés est la suivante :

- Toutes les versions des navigateurs utilisées par plus de 0.5% des utilisateurs mondiaux.
- Toutes les versions des navigateurs utilisées par plus de 0.5% des utilisateurs provenant de France, Suisse, Belgique et Canada.
- Quoi qu'il en soit, les deux dernières versions de tous les navigateurs (même si < 0.5% d'utilisation).
- Quoi qu'il en soit, la dernière version de Firefox ESR (Extended Support Release, pour les entreprises).
- __MAIS__ sans inclure les versions des navigateurs considérés comme "[mortes](https://browsersl.ist/#q=dead)".

Ce qui donne [une couverture approximative de 91.5 % des utilisateurs](https://browsersl.ist/#q=%3E+0.5%25%2C%3E+0.5%25+in+FR%2C%3E+0.5%25+in+BE%2C%3E+0.5%25+in+CH%2C%3E+0.5%25+in+CA%2Clast+2+versions%2CFirefox+ESR%2Cnot+dead) (__au moment ou j'écris__).  

---  

@polosson Est-ce qu'on veut mettre ces informations sur le site internet (si oui, est-ce que tu peux ouvrir un ticket dans le bon repo) ?
