### ISSUE TITLE
Indications du parc pour un matériel

### ISSUE THREAD

**Issue by corentindrd** [Robert-2/Robert2#390]
Quand on clique sur un matériel dans la liste du matériel, il faudrait une indication pour connaitre le parc dans lequel il est.
Comme le texte qui indique la catégorie dans lequel il est.

**Comment by polosson** [comment]
Bonjour @corentindrd !

Sauf erreur de ma part, c'est déjà le cas, cette information est visible à droite de l'écran dans la fiche d'un matériel : 

![Screenshot_20230724_163608](https://github.com/Robert-2/Robert2/assets/1675719/74e55b33-ffdc-4d34-943c-2d33d47e1d15)

Si ce n'est pas le cas, alors c'est qu'il s'agit d'un matériel identifié de manière "unitaire" (une [fonctionnalité Premium](https://robertmanager.org/premium-features#premium-features-material-units)), et que l'information est visible au niveau de chaque unité de ce matériel.

Ou alors, j'ai peut-être mal compris et il s'agit-il d'un autre endroit dans le logiciel ?

**Comment by corentindrd** [comment]
Bonjour @polosson 

Effectivement sur ta photo c'est bien le cas mais moi je n'ai rien, sur aucun matériel et j'ai bien la dernière version (non premium).
<img width="197" alt="image" src="https://github.com/Robert-2/Robert2/assets/66335806/3ff71199-5b3f-4bb0-bd7b-044480e7a4b4">

**Comment by polosson** [comment]
Ahhhh autant pour moi !

Exact, je suis sur la prochaine version (0.22 qui va sortir très bientôt)... Car c'est quelque chose qu'on a ajouté récemment ! Donc bientôt disponible :slightly_smiling_face:

Merci, je ferme donc ce ticket. Cheers !
