### ISSUE TITLE
Remise sur des matériels dans un devis

### ISSUE THREAD

**Issue by corentindrd** [Robert-2/Robert2#391]
Bonjour,

Il faudrait ajouter une fonction qui permet de faire une remise sur un ou plusieurs matériel de la liste dans un devis, actuellement il n'est possible que de faire une remise sur le total.

Bonne journée

**Comment by polosson** [comment]
Bonjour @corentindrd 
Cette fonctionnalité a été implémentée dans la version 1.0 de Loxya qui est sortie le 6 décembre 2024.
