### ISSUE TITLE
Suppression des bénéficiaires incomplète

### ISSUE THREAD

**Issue by LaplancheMaxime** [Robert-2/Robert2#394]
Bonjour messieurs, 

Petit souci lors de la suppression d'un bénéficiaire (après l'avoir supprimer de la corbeille des bénéficiaires) : 
```json
{
    "success": false,
    "error": {
        "code": 400,
        "message": "Validation failed.",
        "details": {
            "email": [
                "Cette adresse e-mail est déjà utilisée"
            ]
        }
    }
}
```
Depuis l'api ou l'interface, il n'est pas possible de créer un bénéficiaire avec un email créé déjà utilisé auparavant. Les utilisateurs sont-ils réellement supprimés ?
Version de loxya utilisée : 0.22.1

Bon courage

**Comment by Donov4n** [comment]
Bonjour !

Pour confirmer, vous dîtes qu'après avoir supprimé un bénéficiaire, puis être passé par la corbeille et l'avoir, ce coup-ci, supprimé "définitivement", l'adresse e-mail qui lui était assignée n'est toujours pas utilisable avec l'erreur citée ?

**Comment by LaplancheMaxime** [comment]
Bonjour
C'est exactement ça.

**Comment by polosson** [comment]
Bonjour !

Alors je pense que cela peut venir du fait que la personne existe dans les techniciens (car les bénéficiaires et les techniciens partagent la table `persons` via un champ `person_id`, dans laquelle se trouve l'adresse e-mail).

Il n'y a pas encore de moyen de créer un bénéficiaire qui est déjà technicien dans le logiciel, il faut passer par la base de données en ajoutant une entrée dans la table `beneficiaries` et lui passer l'ID de la personne (trouvée dans la table `persons`) dans le champ `person_id`.

Merci de nous dire si c'est bien ça le souci ! :slightly_smiling_face:

**Comment by LaplancheMaxime** [comment]
Bonjour,

Le problème ne rentre pas dans ce cas de figure. 
Workflow pour reproduire : 
- Création d'un bénéficiaire avec l'adresse toto@gmail.com
- Mise à la corbeille du bénéficiaire
- Suppression du bénéficiaire dans la corbeille
- Création d'un bénéficiaire avec l'adresse toto@gmail.com -> **Cette adresse e-mail est déjà utilisée**

L'adresse toto@gmail.com n'est pas utilisée par les techniciens

**Comment by LaplancheMaxime** [comment]
Pas de souci, je vais faire le tri dans la base de données!
Merci à vous 👍

**Comment by polosson** [comment]
OK, corrigé dans la version 0.22.2 ! 🙂
