### ISSUE TITLE
Problème d'ajout de PDF dans un matériel

### ISSUE THREAD

**Issue by corentindrd** [Robert-2/Robert2#398]
L'import de PDF dans l'onglet document d'un matériel ne fonctionne pas pour moi, mais bien fonctionnel pour un évènement.

**Comment by Donov4n** [comment]
Bonjour, quand vous dites que ça ne fonctionne pas, qu'est ce que ça fait au juste ? Pouvez-vous donner des détails ?

Pour nous permettre de cibler le souci, vous pouvez récupérer le détail de l'erreur qui se produit lors de l'upload en suivant les informations de la vidéo ci-contre et coller le résultat ici: https://www.youtube.com/watch?v=-Ri4ocjBqc4

**Comment by corentindrd** [comment]
Bonjour,

Merci de votre réponse rapide et votre aide sur comment récupérer l'erreur, c'était tout simplement un problème de permissions dans le dossier.

Le problème est résolu.

Merci
