### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by morganplancot** [Robert-2/Robert2#400]
Hello I have a problem after the connection to the database step I have this page

![Capture](https://github.com/Robert-2/Robert2/assets/114753584/24d41803-043d-48bc-9970-8b1496319c83)

**Comment by polosson** [comment]
Bonjour @morganplancot, 

Merci de bien vouloir utiliser [le forum officiel du projet](https://forum.robertmanager.org/) pour ce genre de demande d'aide à la résolution de problème. Je crois d'ailleurs que vous avez déjà posté [un message concernant un problème d'installation](https://forum.robertmanager.org/d/375-probleme-pour-linstallation). Si nous n'y avons pas encore répondu, c'est que nous n'avons pas encore trouvé le temps de le faire correctement.

Je vous demande donc de bien vouloir créer un nouveau sujet sur le forum pour ce problème-ci (sauf si c'est la suite du problème que vous avez déjà démarré sur le forum). Mais pour qu'on puisse vous aider, il faudra ajouter les informations suivantes concernant votre problème : 

- quel type de serveur utilisez-vous (apache, NGinx, WAMP...) ?
- quel est le cheminement que vous avez suivi pour en arriver là (toutes les étapes de l'installation)
- quel est l'URL de la page (juste la partie "path", la route) qui pose problème ?
- Est-ce que votre base de données est bien installée et toutes les tables bien présentes ?

Je vous remercie d'avance, et je ferme ce ticket pour continuation sur le forum.
