### ISSUE TITLE
Plus de TVA après MAJ v1.0.2

### ISSUE THREAD

**Issue by Tuxem** [Robert-2/Robert2#411]
Hello,

Sur la version 1.0.2, lorsqu’on génère un devis ou une facture, on obtient "(T.V.A non applicable)".

J’ai essayé dans Paramètres > Facturation - Taxes, de définir une Taxe par défaut puis de l’appliquer et de recréer un nouvel événement et idem.

Dans le settings.json, pour "companyData", j'ai bien "vatRate": 20.

**Comment by Donov4n** [comment]
Bonjour @Tuxem 

Comme spécifié sur la page de mise à jour du site (https://robertmanager.org/wiki/update / Point 2)et sur la release côté Github (https://github.com/Robert-2/Robert2/releases/tag/1.0.0), il faut dorénavant copier le fichier `settings.json` vers le nouveau dossier de l'application avant de se rendre dans l'assistant d'installation (et donc d'exécuter les migrations).  
Est-ce que ceci a été fait ?

En effet, la migration de la base de données se chargera de créer une taxe par défaut en se basat sur l'ancien paramètree `vatRate` de votre fichier `settings.json` puis assignera cette taxe par défaut à tout le matériel existant.

En effet : Maintenant les taxes sont définies par matériel. Si ce que je dis au dessus n'a pas été fait correctement, la migration n'a pas pu créer la taxe par défaut et donc tout votre matériel se retrouve sans taxe.

Pour solutionner le problème (si c'est bien celui-ci); deux options:

- Recommencer la procédure de mise à jour en utilisant un dump de votre base de données antérieur à la mise à jour et veillez à bien mettre l'ancien fichier `settings.json` au bon endroit dans le dossier contenant les sources de la 1.02.
- Ou alors ... modifier chaque matériel pour y assigner la taxe par défaut que vous semblez avoir créé.

Quoi qu'il en soit, si la copie du fichier `settings.json` n'a pas été effectué, le système de migration n'a pas pu non plus créer les règles de dégressivité en se basant sur votre ancien `degressiveRateFunction` donc si c'est quelque chose que vous utilisiez je vous conseille d'opter pour la solution 1.

_Tout ceci suppose qu'il y a eu un souci avec le fichier `settings.json` lors de la mise à jour, si ce n'est pas le cas, merci de donner les étapes pour reproduire le souci._

**Comment by Tuxem** [comment]
Arf... Bah effectivement j'avais fait une mise à jour comme avant 😅

Donc effectivement tout était vide en tva.

Mais du coup il y avait tellement de changement que je n'ai pas vu ce détails très cool d'avoir maintenant une tva par matériel.

Je suis répartis sur un dump pré migration et en copiant le settings... Bah ça fonctionne mieux...

Le bug était donc mon incapacité à lire un Readme désolé 😅

Merci pour cette réponse rapide, précise et juste.
