### ISSUE TITLE
Champs e-mail disparu sur la v1.0.2 dans les bénéficiaires

### ISSUE THREAD

**Issue by Tuxem** [Robert-2/Robert2#412]
Lorsqu’on crée ou qu’on modifie un bénéficiaire (personne et société), le champs e-mail n’es plus présent.

Néanmoins sur les anciens qui avaient des emails, ils sont bien affichés dans l’onglet "informations"

v1.0.2

**Comment by Donov4n** [comment]
En effet, le champ ne semble plus apparaitre (version 1.0.2 OSS) je ping @polosson pour qu'il s'occupe de corriger ça.

**Comment by polosson** [comment]
Done, corrigé dans la version 1.0.3.
Merci @Tuxem pour le signalement :+1: 
Cheers !
