### ISSUE TITLE
Renommer "Bénéficiaire" en "Emprunteur" dans toute l'application

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#44]

**Comment by Donov4n** [comment]
Au final, tu t'en occupes ? Car je pensais le faire en t'en parlant

**Comment by adamlarat** [comment]
Salut, chuis de retour ! 
Je viens de lancer une install de 'prod' pour une vingtaine d'utilisateurs. C'est amené à grossir vers une centaine d'utilisateurs…
Lors de l'install, il est demandé comment doivent s'appeler les Bénéficiaires et Techniciens dans l'appli et j'ai rempli les champs avec 'Emprunteur·se' et 'Prêteur·se'. C'est bien stocké dans la DB mais ça ne change rien dans l'appli : 
![Capture d’écran de 2021-06-15 16-29-09](https://user-images.githubusercontent.com/1625270/122071249-e1ddf200-cdf6-11eb-878d-f9cacfb4c93f.png)
![Capture d’écran de 2021-06-15 16-28-52](https://user-images.githubusercontent.com/1625270/122071275-e73b3c80-cdf6-11eb-8981-577167b48b93.png)
Du coup j'écris ici pour savoir est-ce que je me lance dans la mission de remplacer toutes les occurences de Bénéficiaires par la chaîne de caractère stockées avec le tag 1 dans DB.tags et Techniciens par celle stockées avec le tag 2 ?
Ou alors, vous vouliez remplacer Bénéficiaire par Emprunteur en dur partout dans le code ?

**Comment by polosson** [comment]
Hello @adamlarat !

En effet, nous avons prévu de renommer ceci "en dur" dans l'appli (dans les fichiers de traduction i18n). Ce qui est demandé dans l'assistant d'installation c'est uniquement le nom de tags utilisés pour identifier les `Person` en tant que bénéficiaires ou techniciens. Il est vrai que c'est un non-sens de demander cela lors de l'installation (ça devrait rester des tags connus du système uniquement, pas des utilisateurs)... Mais ça a été fait ainsi à l'époque...

Dans l'idéal, il faudrait supprimer ceci de l'étape d'install, et même enlever la possibilté de modifier ceci dans la config (les noms des tags doivent rester dans la config, mais ne devraient pas pouvoir être modifiés par les utilisateurs).

En tout cas ce qui est sûr, c'est qu'on ne peut pas se baser sur des tags arbitrairement choisis par un utilisateur pour le nom des menus et autres occurrences de ces termes (dans les listings, les select, les PDF...).

Si tu as la motivation de remplacer le terme "bénéficiaire" par "emprunteur" dans toute l'application (aussi bien côté front-end que côté back-end, attention), c'est avec plaisir qu'on acceptera ta PR !! :smile:

Merci Adam, cheers !

**Comment by Donov4n** [comment]
Au final, dans la 0.20.0 on va partir sur la solution suivante:

- L'entité "Bénéficiaires" gardera son nom, donc: 
   - dans les events, on sélectionnera toujours un ou plusieurs bénéficiaire(s)
   - le menu bénéficiaires restera présent

- Le système de reconnaissance par tag va être supprimé au profit de tables `beneficiaries` / `technicians`.

- Une nouvelle notion d'emprunt va être implémentée dans la version 20.0.0 et à terme il sera possible de désactiver les événements si l'activité de l'entité utilisant Robert2 / Loxya ne les utilisent pas. Pour la notion d'emprunt, voir #358.

- Dans le cadre d'un emprunt, les bénéficiaires seront nommés "emprunteurs".

Je ferme ce ticket.
