### ISSUE TITLE
Changer le terme "Salut" en "Bonjour" en haut de l'application

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#46]

**Comment by Donov4n** [comment]
D'ailleurs, je me demande, est-ce qu'on devrait pas plutôt laisser uniquement le mail sans forme de salutation ?

**Comment by polosson** [comment]
Hmmm pourquoi pas, ça serait encore moins familier... Mais peut-être un peu trop impersonnel et moins sympa ? Sachant qu'on a la place... Perso je garderais le "Bonjour" :smile:
