### ISSUE TITLE
Edit bénéficiaire : l'entreprise sélectionnée n'apparaît pas dans le select

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#50]
Si un bénéficiaire dispose déjà d'une entreprise, celle-ci n'apparaît pas dans le select du formulaire d'édition du bénéficiaire.

**Comment by polosson** [comment]
Damned, je n'ai pas réussi à reproduire le bug, en local ça fonctionne parfaitement... Très bizarre, à surveiller... En attendant j'annule ce ticket.

**Comment by Donov4n** [comment]
On devrait peut être checker ensemble Jeudi ?

A voir si ça vient d'un oubli dans mon insertion de données.

**Comment by polosson** [comment]
Hmmm tu as raison, let's check it further... Je re-ouvre.
