### ISSUE TITLE
Comment faire la mise à jour vers Robert 2 0.10.0

### ISSUE THREAD

**Issue by ftnonen** [Robert-2/Robert2#53]
Bonjour ;
Merci de bien vouloir me conseiller pour la mise à jour chez Ionos.
Un remplacement des fichiers est suffisant ?
Salutations

**Comment by Donov4n** [comment]
Bonjour,

Pour la procédure de mise à jour de Robert2, vous pouvez consulter la [page de la documentation dédiée](https://robertmanager.org/wiki/update).

Pour toute autre question, merci de passer par le [forum de Robert2](https://forum.robertmanager.org/).  
_(Cet endroit (Github) étant dédié aux rapports de bugs et demandes de fonctionnalités)_

Si vous avez besoin d'une aide personnalisée, vous pouvez passer par la [page de contact](https://robertmanager.org/contact) et nous reviendrons vers vous.
