### ISSUE TITLE
"Class 'Twig_SimpleFunction' not found" 

### ISSUE THREAD

**Issue by Tuxem** [Robert-2/Robert2#54]
Salutations,

Lors d'une mise à jour (0.9 vers 0.10) j'ai eut une erreur 500 avec "Class 'Twig_SimpleFunction' not found".

En cherchant un peu, il semblerai que Twig_SimpleFunction ait été retiré depuis la version 3 de Twig.

J'ai donc appliqué les modifs suivantes pour que cela refoncitonne à nouveau : 

```
diff --git a/server/src/App/Controllers/HomeController.php b/server/src/App/Controllers/HomeController.php
index 0042209..d695262 100644
--- a/server/src/App/Controllers/HomeController.php
+++ b/server/src/App/Controllers/HomeController.php
@@ -208,9 +208,9 @@ class HomeController
     private function _bindCustomTwigFunctions(): void
     {
         $i18n = new I18n();
-        $translate = new \Twig_SimpleFunction('translate', [$i18n, 'translate']);
-        $version = new \Twig_SimpleFunction('version', $this->getVersion());
-        $serverConfig = new \Twig_SimpleFunction('serverConfig', $this->getServerConfig());
+        $translate = new \Twig\TwigFunction('translate', [$i18n, 'translate']);
+        $version = new \Twig\TwigFunction('version', $this->getVersion());
+        $serverConfig = new \Twig\TwigFunction('serverConfig', $this->getServerConfig());
 
         $this->view->getEnvironment()->addFunction($translate);
         $this->view->getEnvironment()->addFunction($version);
```

J'ai pas creusé plus, mais ça pourrai vous intéresser ^^ Si vous avez besoin de plus d'infos, je reste à disposition.
J'ai fait la MAJ comme indiqué sur le wiki, rien de plus, rien de moins :)

En tout cas, super projet ! Si j'arrive à trouver un peu de temps, j'aimerai vraiment vous aider :)

**Comment by Donov4n** [comment]
Bonjour @Tuxem,

En effet, nous avons remarqué qu'il y avait un souci avec `Twig_SimpleFunction` mais le `composer.lock` 
nous permettait de reporter la mise à jour de cette dépendance à la prochaine version de Robert.

Mais c'était sans compter que dans la doc de mise à jour on indique d'exécuter `composer update` ... 😄 

---

Votre modification me semble être suffisante pour une pull-request, vous sentez-vous d'en soumettre une ?  
Il faudra évidemment aussi joindre le nouveau `composer.json` / `.lock`, avec l'update des dependencies Twig.

Dans tous les cas, merci pour votre intérêt pour Robert2 !

**Comment by Tuxem** [comment]
@Donov4n, j'ai ouvert la PR #55.

D'ailleurs, si jamais il m'arrive de participer au projet, vous avez un outil de test ? et éventuellement une page sur vos best practices ? Sur le site je n'ai pas trouvé ce genre d'infos :)

**Comment by Donov4n** [comment]
Merci beaucoup pour la PR, je regarde ça rapidement.

Pour ce qui est des tests, nous utilisons PHPUnit pour les tests backs et Jest pour les tests fronts.  
Pour ce qui est des tests backs, il y a quelques infos dans le [CONTRIBUTING.md](https://github.com/Robert-2/Robert2/blob/master/server/CONTRIBUTING.md#running-tests).
