### ISSUE TITLE
Définir un host local d'API de développement pour Robert + le documenter

### ISSUE THREAD

**Issue by Donov4n** [Robert-2/Robert2#63]
Actuellement, il y a `http://robert2.etoilenoire` [d'hardcodé](https://github.com/Robert-2/Robert2/blob/0.10.1/client/src/config/globalConfig.js#L4) dans la configuration de développement pour le host de l'API.  

On devrait sans doute définir un host de développement "conseillé", du genre `robert.local` (ou `robert2.local`)  
que l'on puisse documenter dans le CONTRIBUTING.md là ou on parle de `yarn start` et aussi remplacer dans le fichier
linké ci-dessus.

**Comment by Donov4n** [comment]
@polosson Si tu as un avis sur la question

**Comment by polosson** [comment]
Yeah ! Je pense en effet que partir sur `robert.local` est une bonne idée :smile:

Dans l'idéal il faudrait que ça soit plutôt dans une variable d'environnement, mais je crois que c'est pas pris en charge par vue-cli (ou alors j'ai pas assez creusé ?) Mais en attendant, ta solution semble bonne en effet ! :+1:
