### ISSUE TITLE
Ajout d'un champs poids

### ISSUE THREAD

**Issue by Tuxem** [Robert-2/Robert2#68]
Il pourrait être intéressant d'avoir le poids total du matériel pour un événement pour le chargement des camions. Peut-être même aussi dans le détails de la fiche de départ pour que les techniciens puissent savoir quel poids fait une lumière, une enceinte s'ils veulent les accrocher.

**Comment by polosson** [comment]
Hello @Tuxem, merci pour le message :slightly_smiling_face: !

Il faudrait plutôt utiliser [le forum du projet](https://forum.robertmanager.org) pour ce genre d'idées, car cela permet aux autres utilisateurs (qui ne maîtrisent pas Github) de suivre les conversations et apporter leurs idées aussi ! Aussi, ça nous aide pour mieux gérer toutes les demandes de centraliser cela sur le forum.

Puis-je donc vous demander d'ouvrir un sujet sur le forum pour en parler, svp ? On se fera une joie d'y répondre.
Merci d'avance !

**Comment by Tuxem** [comment]
Salutations @polosson , pertinent, je l'ai ouvert sur https://forum.robertmanager.org/d/150
Merci à vous !
