### ISSUE TITLE
Préciser le(s) champ(s) qui empêche(nt) la création si existe déjà

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#7]
En effet, il peut être déroutant pour l'utilisateur d'avoir le message *« Cet enregistrement existe déjà »* sans savoir pourquoi. Voir [cette discussion](https://forum.robertmanager.org/d/113-probleme-nouveau-materiel) du forum.

Il faudrait donc préciser dans le message quel(s) champ(s) provoque cette erreur.

**Comment by Donov4n** [comment]
Je ferme étant donné que ça a été géré depuis.
