### ISSUE TITLE
Ajouter un trim() auto sur les champs string lors du save

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#87]
Actuellement on peut sauvegarder des champs avec des espaces en début et fin de chaîne, et ça pose problème ensuite lors d'un getAll si on trie sur ce champ, il n'est plus bon du coup...

Il faudrait trouver un moyen d'appliquer systématiquement un `trim()` sur la valeur des champs de type `string` juste avant sauvegarde.

**Comment by polosson** [comment]
@Donov4n j'ai oublié de te parler de ce ticket tout à l'heure, je veux bien que te me dises ce que tu en penses à l'occasion, et si tu as une idée de la meilleure manière de où mettre ceci. Quand tu auras le temps, thanks ! :slightly_smiling_face:

**Comment by Donov4n** [comment]
> @Donov4n j'ai oublié de te parler de ce ticket tout à l'heure, je veux bien que te me dises ce que tu en penses à l'occasion, et si tu as une idée de la meilleure manière de où mettre ceci. Quand tu auras le temps, thanks ! 🙂

En effet, ça me semble utile, quand à savoir comment mettre ça en place ... Je regarderai du côté des [mutateurs](https://laravel.com/docs/8.x/eloquent-mutators#defining-a-mutator).  
Reste que je suis pas certain que ce soit call lors d'un instanciation avec attributes sous forme "bulk" (`new Model([...attrs])`).

Sinon, peut-être monkey-patcher le save dans le baseModel en utilisant la propriété `$casts` pour savoir qui trimer ?
