### ISSUE TITLE
Ajout du type "date" dans les caractéristiques spéciales de matériel

### ISSUE THREAD

**Issue by polosson** [Robert-2/Robert2#90]
- [x] Ajouter la possibilité de définir des caractéristiques spéciales de type "date" (Ui + Db). Ici : ![](https://user-images.githubusercontent.com/3775007/102479786-a3da5e00-405f-11eb-939f-82ad09f8ac57.png) 
- [ ] ~~Prendre en charge la validation des inputs utilisateur pour ces champs de type date.~~

**Comment by polosson** [comment]
À propos du second point, je ne me souviens plus très bien ce qu'on avait dit mais ça ne me semble pas vraiment nécessaire vu qu'on peut utiliser le datepicker...
Si jamais tu as une idée de ce que c'était plus précisément ce second point @Donov4n  ? Sinon, on peut faire au plus simple et se contenter du datepicker à mon avis. :smile:

**Comment by Donov4n** [comment]
> À propos du second point, je ne me souviens plus très bien ce qu'on avait dit mais ça ne me semble pas vraiment nécessaire vu qu'on peut utiliser le datepicker...
> Si jamais tu as une idée de ce que c'était plus précisément ce second point @Donov4n ? Sinon, on peut faire au plus simple et se contenter du datepicker à mon avis. 😄

Il s'agissait ici de valider côté BO que la date est bien ... une date.  
(Via une règle de validation custom qui tiens compte du type de champs)

Le soucis de faire ça qu'avec le datepicker c'est que techniquement, ils envoient ce qu'ils veulent via l'API.  
Mais comme tu veux pour faire au plus rapide (mais si c'est le cas, peut être ouvrir un ticket, histoire de garder une API assez solide)

**Comment by polosson** [comment]
Alors en fait, actuellement il n'y a même pas du tout de validation côté serveur pour les valeurs des caractéristiques spéciales de matériel ! J'ai ouvert le ticket #96 en ce sens du coup, on le fera un de ces jours, là il faut qu'on avance. :smile:
